#!/usr/bin/env node
// Builds media/logos.js and media/logos/*-{dark,light}.svg (AC-65) from design/logo-sources/*.svg.
// Sources: Simple Icons 16.32.0 (CC0-1.0): claude, claudecode, anthropic, opencode, github;
// LobeHub Icons @lobehub/icons-static-svg 1.95.1 (MIT): openai, codex. See NOTICE.md.
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const SIMPLE = new Set(['claude', 'claudecode', 'anthropic', 'opencode', 'github']);
const out = {};
for (const file of fs.readdirSync(path.join(__dirname, 'logo-sources')).filter(f => f.endsWith('.svg')).sort()) {
  const name = file.replace(/\.svg$/, '');
  const svg = fs.readFileSync(path.join(__dirname, 'logo-sources', file), 'utf8');
  const rootRule = /<svg[^>]*\sfill-rule="([^"]+)"/.exec(svg);
  const paths = [...svg.matchAll(/<path\b([^>]*?)\/?>(?:<\/path>)?/g)].map(m => {
    const d = /\sd="([^"]+)"/.exec(m[1]);
    const rule = /fill-rule="([^"]+)"/.exec(m[1]) || /clip-rule="([^"]+)"/.exec(m[1]) || rootRule;
    return d && (rule ? { d: d[1], rule: rule[1] } : { d: d[1] });
  }).filter(Boolean);
  if (!paths.length) throw new Error(`no paths in ${file}`);
  out[name] = { viewBox: /viewBox="([^"]+)"/.exec(svg)[1], paths, source: SIMPLE.has(name) ? 'Simple Icons (CC0-1.0)' : 'LobeHub Icons (MIT)' };
  for (const [variant, fill] of [['dark', '#C8C6D4'], ['light', '#4A4660']]) {
    const body = paths.map(p => `<path fill="${fill}"${p.rule ? ` fill-rule="${p.rule}"` : ''} d="${p.d}"/>`).join('');
    fs.writeFileSync(path.join(root, 'media/logos', `${name}-${variant}.svg`), `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${out[name].viewBox}">${body}</svg>\n`);
  }
}
const logos = Object.fromEntries(Object.entries(out).map(([k, v]) => [k, { viewBox: v.viewBox, paths: v.paths }]));
fs.writeFileSync(path.join(root, 'media/logos.js'), `// Provider and harness logos (AC-65), monochrome so they follow the theme (fill: currentColor).
// Generated by design/build-logos.js from design/logo-sources (Simple Icons, CC0-1.0; LobeHub Icons,
// MIT; see NOTICE.md). media/logos/*-dark.svg and *-light.svg are the same marks for native views.
(function () {
  const LOGOS = ${JSON.stringify(logos)};
  const HARNESS = { claude: 'claudecode', codex: 'codex', 'codex-app': 'codex', opencode: 'opencode' };
  const PROVIDER = { anthropic: 'claude', openai: 'openai', local: 'opencode', github: 'github' };
  const NS = 'http://www.w3.org/2000/svg';
  /** An inline, theme-colored logo element, or null when there is none (callers use a codicon). */
  function logo(name, { size = 14, label } = {}) {
    const l = LOGOS[name]; if (!l) return null;
    const svg = document.createElementNS(NS, 'svg'); svg.setAttribute('viewBox', l.viewBox); svg.setAttribute('width', size); svg.setAttribute('height', size); svg.setAttribute('class', 'logo logo-' + name);
    svg.setAttribute('fill', 'currentColor'); if (label) { svg.setAttribute('role', 'img'); svg.setAttribute('aria-label', label); } else svg.setAttribute('aria-hidden', 'true');
    for (const p of l.paths) { const e = document.createElementNS(NS, 'path'); e.setAttribute('d', p.d); if (p.rule) e.setAttribute('fill-rule', p.rule); svg.append(e); }
    return svg;
  }
  window.OverseerLogos = { logo, forHarness: h => HARNESS[h], forProvider: p => PROVIDER[p], names: Object.keys(LOGOS) };
})();
`);
console.log(Object.entries(out).map(([k, v]) => `${k}:${v.paths.length}`).join(' '));
