#!/usr/bin/env python3
"""Writes the README's table of what a phone can do, from protocol/protocol.json (Gate N, AC-127).

    python3 protocol/capabilities.py          rewrite the table in README.md
    python3 protocol/capabilities.py --check  fail when the table is not current

Every daemon method is listed with its phone status: available, the Mac only (with the reason),
or not yet. The gateway's checks are built from the same file, so the table cannot say one thing
while the daemon does another."""
import json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
START, END = "<!-- phone-capabilities:start -->", "<!-- phone-capabilities:end -->"
WHO = {"self": "Every phone", "read": "Every phone", "control": "Full control", "mac_only": "—"}
STATUS = {"available": "Available", "mac_only": "The Mac only", "not_yet": "Not yet"}


def table():
    doc = json.loads((ROOT / "protocol/protocol.json").read_text())
    rows = ["| Method | What it does | On a phone | Who |", "| --- | --- | --- | --- |"]
    order = {"available": 0, "not_yet": 1, "mac_only": 2}
    methods = sorted(doc["methods"].items(), key=lambda kv: (order[kv[1]["phone"]], kv[0]))
    for name, m in methods:
        status = STATUS[m["phone"]]
        if m.get("reason"):
            status += ": " + m["reason"][0].lower() + m["reason"][1:]
        who = WHO[m["class"]] if m["phone"] == "available" else "—"
        rows.append(f"| `{name}` | {m['summary']} | {status} | {who} |")
    counts = {k: sum(1 for _, m in methods if m["phone"] == k) for k in order}
    lead = (f"{len(methods)} methods: {counts['available']} available on a phone, {counts['mac_only']} on the Mac only"
            + (f", {counts['not_yet']} not yet" if counts["not_yet"] else "") + ". "
            "A *watch only* phone reads and cannot change anything. Generated by `python3 protocol/capabilities.py` from `protocol/protocol.json`.")
    return lead + "\n\n" + "\n".join(rows)


def main():
    readme = ROOT / "README.md"
    text = readme.read_text()
    if START not in text or END not in text:
        sys.exit("README.md has no phone capabilities section (the markers are missing)")
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    fresh = head + START + "\n" + table() + "\n" + END + tail
    if "--check" in sys.argv:
        if fresh != text:
            sys.exit("README.md: the phone capabilities table is not current; run python3 protocol/capabilities.py")
        print("the phone capabilities table is current")
        return
    readme.write_text(fresh)
    print("README.md updated")


if __name__ == "__main__":
    main()
