#!/usr/bin/env node
// Writes the app's protocol types from protocol/protocol.json (Gate N, AC-134):
//   node protocol/gen-ts.mjs          write phone/protocol/protocol.generated.ts
//   node protocol/gen-ts.mjs --check  fail when that file is not current
// The daemon's checks are built from the same description, and a daemon test compares real
// results and events with its shapes, so a method cannot change on one side only.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const doc = JSON.parse(readFileSync(join(root, 'protocol/protocol.json'), 'utf8'));
const target = join(root, 'phone/protocol/protocol.generated.ts');
const PRIMITIVES = { string: 'string', number: 'number', boolean: 'boolean', null: 'null', json: 'unknown' };

/** A shape as TypeScript. Returns [type, optional]. */
function ts(shape, indent = '') {
  if (typeof shape === 'object' && shape !== null) {
    const fields = Object.entries(shape).map(([name, s]) => {
      const [type, optional] = ts(s, indent + '  ');
      const key = /^[A-Za-z_][A-Za-z0-9_]*$/.test(name) ? name : JSON.stringify(name);
      return `${indent}  ${key}${optional ? '?' : ''}: ${type}${optional ? ' | null' : ''};`;
    });
    return [fields.length ? `{\n${fields.join('\n')}\n${indent}}` : 'Record<string, never>', false];
  }
  let text = String(shape).trim();
  let optional = false;
  if (text.endsWith('?')) { optional = true; text = text.slice(0, -1); }
  if (text.endsWith('[]')) { const [inner, innerOptional] = ts(text.slice(0, -2), indent); return [`Array<${inner}${innerOptional ? ' | null' : ''}>`, optional]; }
  if (text.startsWith('record<') && text.endsWith('>')) { const [inner] = ts(text.slice(7, -1), indent); return [`Record<string, ${inner}>`, optional]; }
  if (text.includes('|') && !text.includes("'")) return [text.split('|').map(s => ts(s.trim(), indent)[0]).join(' | '), optional];
  if (text.includes("'")) return [text.split('|').map(s => s.trim()).join(' | '), optional];
  if (text in PRIMITIVES) return [PRIMITIVES[text], optional];
  if (!(text in doc.types)) throw new Error(`protocol.json: unknown type ${text}`);
  return [text, optional];
}

const out = [];
out.push('// Generated by protocol/gen-ts.mjs from protocol/protocol.json. Do not edit: change the');
out.push('// description and run `node protocol/gen-ts.mjs`. `--check` fails when this file is not current.');
out.push('');
out.push(`export const PROTOCOL_VERSION = ${doc.version} as const;`);
out.push('');
for (const [name, shape] of Object.entries(doc.types)) {
  const [type] = ts(shape);
  out.push(typeof shape === 'object' ? `export interface ${name} ${type}` : `export type ${name} = ${type};`);
  out.push('');
}
out.push('/** The payload of every kind of event the app reads. Other kinds arrive as `unknown`. */');
out.push('export interface EventPayloads {');
for (const [kind, shape] of Object.entries(doc.events)) out.push(`  ${kind}: ${ts(shape, '  ')[0]};`);
out.push('}');
out.push('');
out.push('export type KnownEventKind = keyof EventPayloads;');
out.push('');
out.push('/** An event whose payload is typed by its kind. */');
out.push('export type TypedEvent = { [K in KnownEventKind]: Omit<Event, \'kind\' | \'payload\'> & { kind: K; payload: EventPayloads[K] } }[KnownEventKind];');
out.push('');
out.push("export type MethodClass = 'self' | 'read' | 'control' | 'mac_only';");
out.push('');
const built = Object.entries(doc.methods).filter(([, m]) => !m.planned);
out.push('/** Every method of the daemon: its class for a phone, its parameters and its result. */');
out.push('export interface Methods {');
for (const [name, m] of built) {
  out.push(`  /** ${m.summary}. ${m.phone === 'mac_only' ? 'The Mac only: ' + m.reason + '.' : ''} */`.replace('.  */', '. */'));
  out.push(`  ${JSON.stringify(name)}: { class: '${m.class}'; params: ${ts(m.params, '  ')[0]}; result: ${ts(m.result, '  ')[0]} };`);
}
out.push('}');
out.push('');
out.push('export type MethodName = keyof Methods;');
out.push('');
out.push('/** Methods a phone may call, by what they need. A control method carries a request id. */');
out.push('export const METHOD_CLASS = {');
for (const [name, m] of built) out.push(`  ${JSON.stringify(name)}: '${m.class}',`);
out.push('} as const satisfies Record<MethodName, MethodClass>;');
out.push('');
out.push("export type PhoneMethod = { [K in MethodName]: Methods[K]['class'] extends 'mac_only' ? never : K }[MethodName];");
out.push("export type ControlMethod = { [K in MethodName]: Methods[K]['class'] extends 'control' ? K : never }[MethodName];");
out.push("export type Params<M extends MethodName> = Methods[M]['params'];");
out.push("export type Result<M extends MethodName> = Methods[M]['result'];");
out.push('');
const text = out.join('\n');

if (process.argv.includes('--check')) {
  if (!existsSync(target) || readFileSync(target, 'utf8') !== text) {
    console.error('phone/protocol/protocol.generated.ts is not current; run node protocol/gen-ts.mjs');
    process.exit(1);
  }
  console.log('the app\'s protocol types are current');
} else {
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, text);
  console.log(`wrote ${target} (${built.length} methods, ${Object.keys(doc.types).length} types, ${Object.keys(doc.events).length} event kinds)`);
}
