// Generated by protocol/gen-ts.mjs from protocol/protocol.json. Do not edit: change the
// description and run `node protocol/gen-ts.mjs`. `--check` fails when this file is not current.

export const PROTOCOL_VERSION = 1 as const;

export type RunStatus = 'queued' | 'starting' | 'running' | 'waiting_for_user' | 'completed' | 'failed' | 'interrupted' | 'disconnected' | 'unknown';

export type Scope = 'full' | 'watch';

export interface Task {
  id: string;
  title: string;
  prompt: string;
  repo_root: string;
  target_ref?: string | null;
  workspace_id: string;
  start_snapshot?: string | null;
  fork_commit?: string | null;
  fork_provenance?: string | null;
  created_ms: number;
  archived_ms?: number | null;
}

export interface Workspace {
  id: string;
  path: string;
  repo_root: string;
  common_dir: string;
  kind: 'worktree' | 'current';
  branch?: string | null;
  owner_run_id?: string | null;
  initial_dirty: unknown;
  created_ms: number;
  removed_ms?: number | null;
}

export interface Attention {
  kind: string;
  request_id: string;
  tool?: string | null;
  input: unknown;
}

export interface Run {
  id: string;
  task_id: string;
  parent_run_id?: string | null;
  harness: string;
  harness_version?: string | null;
  profile_id?: string | null;
  model?: string | null;
  workspace_id: string;
  native_id?: string | null;
  status: RunStatus;
  exit_reason?: string | null;
  created_ms: number;
  ended_ms?: number | null;
  title: string;
  relation_source?: string | null;
  relation_confidence?: string | null;
  capabilities: unknown;
  process_generation: number;
  attention?: Attention | null;
}

export interface Turn {
  id: string;
  run_id: string;
  n: number;
  prompt: string;
  snapshot_id?: string | null;
  started_ms: number;
  ended_ms?: number | null;
  status: string;
}

export interface Profile {
  id: string;
  name: string;
  harness: string;
  home?: string | null;
  is_system: boolean;
  created_ms: number;
}

export interface Event {
  seq: number;
  ts: number;
  task_id?: string | null;
  run_id?: string | null;
  kind: string;
  source: string;
  confidence: string;
  payload: unknown;
}

export interface Change {
  status: string;
  path: string;
  old_path?: string | null;
}

export interface GitStatus {
  branch?: string | null;
  head?: string | null;
  staged: Array<Change>;
  unstaged: Array<Change>;
  untracked: Array<string>;
  conflicted: Array<string>;
}

export interface State {
  cursor: number;
  tasks: Array<Task>;
  runs: Array<Run>;
  workspaces: Array<Workspace>;
  profiles: Array<Profile>;
  turns: Record<string, Array<Turn>>;
  oversight: Record<string, unknown>;
  overseer: unknown;
  daemon: {
    pid: number;
    started_ms: number;
    version: string;
    parser_version: string;
  };
}

export interface Harness {
  harness: string;
  program?: string | null;
  version?: string | null;
  installed: boolean;
  capabilities: unknown;
}

export interface Comparison {
  mode: string;
  label: string;
  base?: string | null;
  available: boolean;
  default?: boolean | null;
  detail?: string | null;
  inherited?: boolean | null;
  provenance?: string | null;
  branch?: string | null;
  snapshot?: unknown | null;
}

export interface FileSide {
  exists: boolean;
  size: number;
  kind: 'text' | 'missing' | 'binary' | 'too_large' | 'link' | 'directory' | 'special';
  text?: string | null;
  note?: string | null;
}

export interface Hunk {
  key: string;
  base_start: number;
  base_lines: Array<string>;
  modified_start: number;
  modified_lines: Array<string>;
  reviewed: boolean;
}

export interface Mark {
  key: string;
  path: string;
  at_ms: number;
  by: string;
}

export interface TreeEntry {
  name?: string | null;
  path: string;
  dir: boolean;
  symlink?: boolean | null;
  status?: string | null;
  changes_inside: number;
  deleted?: boolean | null;
}

export interface NotificationSettings {
  enabled: boolean;
  kinds: {
    permission: boolean;
    question: boolean;
    failure: boolean;
    finished: boolean;
  };
  show_text: boolean;
  token?: string | null;
  environment: string;
  bundle?: string | null;
}

export interface KnownRepo {
  root: string;
  name: string;
  last_used_ms: number;
  exists: boolean;
  branch?: string | null;
  default_branch?: string | null;
}

/** The payload of every kind of event the app reads. Other kinds arrive as `unknown`. */
export interface EventPayloads {
  task_created: {
    task: Task;
    run: Run;
    workspace: Workspace;
  };
  task_archived: {
    archived: boolean;
  };
  turn_started: {
    turn: Turn;
    snapshot?: string | null;
  };
  turn_done: {
    ok: boolean;
    summary?: string | null;
  };
  status: {
    status: RunStatus;
    reason?: string | null;
    why?: string | null;
    evidence?: unknown | null;
    generation?: number | null;
    program?: string | null;
  };
  session: {
    native_id: string;
  };
  output: {
    role: string;
    text: string;
  };
  tool: {
    id?: string | null;
    name: string;
    summary?: string | null;
  };
  tool_result: {
    id?: string | null;
    input?: unknown | null;
    is_error?: boolean | null;
    output?: unknown | null;
    status?: string | null;
  };
  file_activity: {
    paths: Array<string>;
    kind: string;
    attribution: string;
  };
  permission: Attention;
  permission_answered: {
    request_id: string;
    allow: boolean;
    by?: string | null;
  };
  usage: unknown;
  error: {
    class: string;
    message: string;
    request?: unknown | null;
  };
  retention: unknown;
  review_mark: {
    key: string;
    path: string;
    reviewed: boolean;
  };
  review_reject: {
    path: string;
    key: string;
    base: string;
    lines_restored: number;
    lines_removed: number;
    file_removed: boolean;
  };
  pull_request: {
    url: string;
    number: number;
    branch?: string | null;
  };
  remote_command: {
    method: string;
    device: string;
    request_id?: string | null;
  };
  gateway_state: {
    state: 'on' | 'off';
    port?: number | null;
    fingerprint?: string | null;
    closed?: number | null;
  };
  gateway_sessions: {
    sessions: number;
    device: string;
    name: string;
    change: 'connected' | 'disconnected';
  };
  power: {
    awake: boolean;
    why: string;
    runs?: Array<string> | null;
  };
  push: {
    device: string;
    name: string;
    kind: string;
    route: string;
    outcome: 'sent' | 'not_sent';
    why: string;
    fields: Array<string>;
  };
  profile: unknown;
  child: {
    child: Run;
    evidence: unknown;
    workspace: string;
  };
  child_reparented: {
    child_run_id: string;
    parent_run_id: string;
  };
  raw_unparsed: {
    text: string;
    parser_version: string;
  };
  connection: {
    status: unknown;
    previous: unknown;
    first?: boolean | null;
  };
}

export type KnownEventKind = keyof EventPayloads;

/** An event whose payload is typed by its kind. */
export type TypedEvent = { [K in KnownEventKind]: Omit<Event, 'kind' | 'payload'> & { kind: K; payload: EventPayloads[K] } }[KnownEventKind];

export type MethodClass = 'self' | 'read' | 'control' | 'mac_only';

/** Every method of the daemon: its class for a phone, its parameters and its result. */
export interface Methods {
  /** Say who is connecting; returns protocol, version and, for a device, its scope. */
  "hello": { class: 'self'; params: {
    client?: string | null;
  }; result: unknown };
  /** Keep the session alive; returns the daemon's time. */
  "ping": { class: 'self'; params: Record<string, never>; result: {
    now_ms: number;
  } };
  /** Replay events after a cursor, then stream live events. */
  "events.subscribe": { class: 'self'; params: {
    after?: number | null;
    run_id?: string | null;
  }; result: {
    subscribed: boolean;
    after: number;
    history_truncated: boolean;
  } };
  /** Read or change this device's notification switches and push token. */
  "device.notifications": { class: 'self'; params: {
    enabled?: boolean | null;
    show_text?: boolean | null;
    kinds?: unknown | null;
    token?: string | null;
    environment?: string | null;
    bundle?: string | null;
  }; result: NotificationSettings };
  /** Every task, run, workspace and account profile. */
  "state": { class: 'read'; params: Record<string, never>; result: State };
  /** Installed harnesses with versions and capabilities. */
  "harness.list": { class: 'read'; params: Record<string, never>; result: Array<Harness> };
  /** Account profiles. */
  "profile.list": { class: 'read'; params: Record<string, never>; result: Array<Profile> };
  /** Sign-in state of one account profile. */
  "profile.status": { class: 'read'; params: {
    id: string;
  }; result: {
    profile_id: string;
    installed: boolean;
    logged_in: boolean;
    program?: string | null;
    version?: string | null;
    method?: string | null;
    identity?: unknown | null;
    detail?: string | null;
    account?: unknown | null;
    expires_ms?: number | null;
    note?: string | null;
  } };
  /** Branches, head and status of a repository Overseer knows. */
  "repo.inspect": { class: 'read'; params: {
    path: string;
  }; result: {
    root: string;
    head?: string | null;
    branch?: string | null;
    default_branch?: string | null;
    branches: Array<string>;
    status: GitStatus;
  } };
  /** The repositories Overseer has used. */
  "repo.known": { class: 'read'; params: Record<string, never>; result: {
    repos: Array<KnownRepo>;
  } };
  /** Files of a worktree or repository, for mentions. */
  "repo.files": { class: 'read'; params: {
    workspace_id?: string | null;
    repo?: string | null;
    query?: string | null;
    limit?: number | null;
  }; result: {
    root: string;
    files: Array<string>;
  } };
  /** The end of a run's raw output. */
  "run.raw_output": { class: 'read'; params: {
    run_id: string;
    max_bytes?: number | null;
  }; result: {
    lines: Array<unknown>;
    truncated: boolean;
    note?: string | null;
  } };
  /** The turns of a run. */
  "run.turns": { class: 'read'; params: {
    run_id: string;
  }; result: Array<Turn> };
  /** Runs that are active now. */
  "run.active": { class: 'read'; params: Record<string, never>; result: Array<Run> };
  /** A page of events. */
  "events.list": { class: 'read'; params: {
    run_id?: string | null;
    after?: number | null;
    limit?: number | null;
  }; result: {
    events: Array<Event>;
    oldest_retained?: number | null;
  } };
  /** The comparisons a run offers. */
  "comparison.options": { class: 'read'; params: {
    run_id: string;
    branch?: string | null;
  }; result: {
    run_id: string;
    workspace: Workspace;
    head?: string | null;
    branch?: string | null;
    branches: Array<string>;
    options: Array<Comparison>;
  } };
  /** The diff of a workspace against a comparison. */
  "workspace.diff": { class: 'read'; params: {
    workspace_id: string;
    base: string;
    status?: boolean | null;
  }; result: {
    workspace_id: string;
    root: string;
    base: string;
    current_tree: string;
    index_tree: string;
    head?: string | null;
    changes: Array<Change>;
    status?: GitStatus | null;
  } };
  /** Git status of a workspace. */
  "workspace.status": { class: 'read'; params: {
    workspace_id: string;
  }; result: GitStatus };
  /** Changed files of a workspace since the task started. */
  "workspace.changes": { class: 'read'; params: {
    workspace_id: string;
  }; result: {
    files: number;
    added: number;
    removed: number;
    names: Array<string>;
    base?: string | null;
  } };
  /** One directory of a worktree. */
  "workspace.tree": { class: 'read'; params: {
    workspace_id: string;
    dir?: string | null;
  }; result: {
    workspace_id: string;
    root: string;
    dir: string;
    base?: string | null;
    entries: Array<TreeEntry>;
    total: number;
    truncated: boolean;
    changed_total: number;
  } };
  /** One file of a workspace, at a comparison and in the working copy. */
  "workspace.file": { class: 'read'; params: {
    workspace_id: string;
    path: string;
    base?: string | null;
  }; result: {
    workspace_id: string;
    path: string;
    base?: string | null;
    before: FileSide;
    now: FileSide;
  } };
  /** The changes of one file as hunks, with their keys and reviewed marks. */
  "workspace.hunks": { class: 'read'; params: {
    workspace_id: string;
    path: string;
    base: string;
    run_id?: string | null;
  }; result: {
    workspace_id: string;
    path: string;
    base: string;
    shown: boolean;
    why?: string | null;
    hunks: Array<Hunk>;
    before: {
      exists: boolean;
      kind: string;
      lines?: number | null;
    };
    now: {
      exists: boolean;
      kind: string;
      lines?: number | null;
    };
  } };
  /** What cleaning up a worktree would remove. */
  "workspace.cleanup_plan": { class: 'read'; params: {
    workspace_id: string;
  }; result: {
    workspace: Workspace;
    active_runs: Array<unknown>;
    dirty?: GitStatus | null;
    removable: boolean;
    reason: string;
  } };
  /** What opening a pull request would do. */
  "workspace.pr_plan": { class: 'read'; params: {
    workspace_id: string;
  }; result: unknown };
  /** What merging back would do. */
  "workspace.merge_plan": { class: 'read'; params: {
    workspace_id: string;
  }; result: unknown };
  /** The hunks marked reviewed for a run. */
  "review.marks": { class: 'read'; params: {
    run_id: string;
  }; result: {
    run_id: string;
    keys: Array<string>;
    marks: Array<Mark>;
  } };
  /** Accounts with sign-in state and plan. */
  "account.list": { class: 'read'; params: Record<string, never>; result: {
    accounts: Array<unknown>;
    providers: Array<unknown>;
  } };
  /** Usage and limits of one account. */
  "account.usage": { class: 'read'; params: {
    id: string;
  }; result: unknown };
  /** Search tasks and runs. */
  "search": { class: 'read'; params: {
    query?: string | null;
    limit?: number | null;
  }; result: {
    task_ids: Array<string>;
    ms: number;
  } };
  /** The last background notice. */
  "daemon.last_notice": { class: 'read'; params: Record<string, never>; result: {
    notice?: unknown | null;
  } };
  /** How many watching UIs are connected. */
  "daemon.clients": { class: 'read'; params: Record<string, never>; result: {
    vscode: number;
    ui: number;
  } };
  /** Start an agent. */
  "task.create": { class: 'control'; params: {
    repo: string;
    harness: string;
    prompt: string;
    title?: string | null;
    workspace_mode?: 'worktree' | 'current' | null;
    profile_id?: string | null;
    target_ref?: string | null;
    model?: string | null;
    effort?: string | null;
    permission_mode?: string | null;
    images?: Array<unknown> | null;
  }; result: {
    task: Task;
    run: Run;
    workspace: Workspace;
  } };
  /** Archive or restore a task. */
  "task.archive": { class: 'control'; params: {
    task_id: string;
    archived?: boolean | null;
  }; result: {
    task_id: string;
    archived_ms?: number | null;
  } };
  /** Send a message to an agent. */
  "run.follow_up": { class: 'control'; params: {
    run_id: string;
    prompt: string;
    model?: string | null;
    effort?: string | null;
    permission_mode?: string | null;
    images?: Array<unknown> | null;
  }; result: Turn };
  /** Stop an agent's turn. */
  "run.interrupt": { class: 'control'; params: {
    run_id: string;
  }; result: unknown };
  /** Allow or deny a permission request. */
  "run.permission": { class: 'control'; params: {
    run_id: string;
    request_id: string;
    allow: boolean;
    message?: string | null;
  }; result: {
    ok: boolean;
  } };
  /** Stop every active agent; the daemon keeps running. */
  "runs.stop_all": { class: 'control'; params: Record<string, never>; result: {
    interrupted: Array<string>;
    failed: Array<unknown>;
  } };
  /** Remove a finished agent's worktree. */
  "workspace.cleanup": { class: 'control'; params: {
    workspace_id: string;
    discard_dirty?: boolean | null;
  }; result: unknown };
  /** Commit and prepare the branch for a pull request. */
  "workspace.pr_prepare": { class: 'control'; params: {
    workspace_id: string;
  }; result: unknown };
  /** Open the pull request with the Mac's Git and GitHub credentials. */
  "workspace.pr_open": { class: 'control'; params: {
    workspace_id: string;
    title?: string | null;
    body?: string | null;
    draft?: boolean | null;
  }; result: {
    url: string;
    number: number;
    reused: boolean;
    branch: string;
    target: string;
    repo: string;
    committed: unknown;
    head: string;
  } };
  /** Record a pull request that was opened. */
  "workspace.pr_opened": { class: 'control'; params: {
    workspace_id: string;
    url: string;
    number?: number | null;
  }; result: {
    recorded: boolean;
  } };
  /** Prepare merging back. */
  "workspace.merge_prepare": { class: 'control'; params: {
    workspace_id: string;
    handoff?: boolean | null;
  }; result: unknown };
  /** Say conflicts are resolved. */
  "workspace.merge_resolved": { class: 'control'; params: {
    workspace_id: string;
  }; result: unknown };
  /** Complete merging back. */
  "workspace.merge_complete": { class: 'control'; params: {
    workspace_id: string;
  }; result: unknown };
  /** Abort merging back. */
  "workspace.merge_abort": { class: 'control'; params: {
    workspace_id: string;
  }; result: unknown };
  /** Mark a hunk reviewed. */
  "review.accept": { class: 'control'; params: {
    run_id: string;
    path: string;
    key: string;
    modified_start?: number | null;
    modified_lines?: Array<string> | null;
    base_lines?: Array<string> | null;
    anchor?: string | null;
  }; result: {
    key: string;
    reviewed: boolean;
  } };
  /** Remove a hunk's reviewed mark. */
  "review.unaccept": { class: 'control'; params: {
    run_id: string;
    key: string;
  }; result: {
    key: string;
    reviewed: boolean;
    changed: boolean;
  } };
  /** Hand the daemon marks a surface kept before. */
  "review.import": { class: 'control'; params: {
    run_id: string;
    marks: Array<unknown>;
  }; result: {
    added: number;
  } };
  /** Revert a hunk in the worktree. */
  "review.reject": { class: 'control'; params: {
    workspace_id: string;
    path: string;
    base: string;
    key: string;
  }; result: {
    path: string;
    rejected: boolean;
    file_removed: boolean;
  } };
  /** Add an account profile. */
  "profile.create": { class: 'control'; params: {
    name: string;
    harness: string;
  }; result: Profile };
  /** Rename an account profile. */
  "profile.rename": { class: 'control'; params: {
    id: string;
    name: string;
  }; result: {
    ok: boolean;
  } };
  /** Sign an account profile out. */
  "profile.logout": { class: 'control'; params: {
    id: string;
  }; result: unknown };
  /** Sign in with the provider's device code, in the phone's browser. */
  "profile.device_login": { class: 'control'; params: {
    id: string;
  }; result: {
    profile_id: string;
    finished: boolean;
    url?: string | null;
    code?: string | null;
    valid_ms?: number | null;
    exit?: number | null;
    logged_in?: unknown | null;
    output?: string | null;
  } };
  /** Add an account. */
  "account.create": { class: 'control'; params: {
    provider: string;
    name: string;
  }; result: {
    account: Profile;
    provider: string;
  } };
  /** Remove an account. */
  "account.remove": { class: 'control'; params: {
    id: string;
  }; result: {
    removed: string;
  } };
  /** Stop the daemon. The Mac only: A phone that stopped the daemon could not start it again. */
  "daemon.shutdown": { class: 'mac_only'; params: unknown; result: unknown };
  /** Stop every agent and the daemon. The Mac only: It stops the daemon; a phone uses runs.stop_all. */
  "daemon.stop_all": { class: 'mac_only'; params: unknown; result: unknown };
  /** Post the background notice. The Mac only: It belongs to the Mac's own notifications. */
  "daemon.background_notice": { class: 'mac_only'; params: unknown; result: unknown };
  /** Post a test notification on the Mac. The Mac only: It belongs to the Mac's own notifications. */
  "daemon.test_notice": { class: 'mac_only'; params: unknown; result: unknown };
  /** The sign-in command for a terminal. The Mac only: It needs a terminal on the Mac; a phone uses profile.device_login. */
  "profile.login_command": { class: 'mac_only'; params: unknown; result: unknown };
  /** Phone access: on or off, port, connected phones. The Mac only: Phone access is managed on the Mac. */
  "gateway.status": { class: 'mac_only'; params: unknown; result: unknown };
  /** Turn phone access on. The Mac only: Phone access is switched on the desktop only. */
  "gateway.enable": { class: 'mac_only'; params: unknown; result: unknown };
  /** Turn phone access off. The Mac only: Phone access is switched on the desktop only. */
  "gateway.disable": { class: 'mac_only'; params: unknown; result: unknown };
  /** Read or change gateway settings. The Mac only: Phone access is managed on the Mac. */
  "gateway.settings": { class: 'mac_only'; params: unknown; result: unknown };
  /** Open pairing and return the pairing code. The Mac only: Pairing starts on the Mac. */
  "gateway.pair_start": { class: 'mac_only'; params: unknown; result: unknown };
  /** Close pairing. The Mac only: Pairing starts on the Mac. */
  "gateway.pair_cancel": { class: 'mac_only'; params: unknown; result: unknown };
  /** Accept or decline a phone that asked to pair. The Mac only: The owner confirms on the Mac. */
  "gateway.pair_confirm": { class: 'mac_only'; params: unknown; result: unknown };
  /** Paired devices. The Mac only: Devices are managed on the Mac. */
  "gateway.devices": { class: 'mac_only'; params: unknown; result: unknown };
  /** Revoke a device. The Mac only: A phone that could manage devices could let another one in. */
  "gateway.device_revoke": { class: 'mac_only'; params: unknown; result: unknown };
  /** Change a device's scope. The Mac only: A phone could raise its own scope. */
  "gateway.device_scope": { class: 'mac_only'; params: unknown; result: unknown };
  /** Rename a device. The Mac only: Devices are managed on the Mac. */
  "gateway.device_rename": { class: 'mac_only'; params: unknown; result: unknown };
  /** Which agent a window on the Mac is looking at. The Mac only: It describes the Mac's own windows. */
  "ui.focus": { class: 'mac_only'; params: unknown; result: unknown };
  /** Audio Mode: on or off, the track and the cues. */
  "audio.get": { class: 'read'; params: Record<string, never>; result: unknown };
  /** The Mac's installed voices for System voice. */
  "audio.voices": { class: 'read'; params: Record<string, never>; result: unknown };
  /** Change Audio Mode. The Mac only: Audio Mode plays on the Mac; it is set there. */
  "audio.set": { class: 'mac_only'; params: unknown; result: unknown };
  /** Play a cue on the Mac. The Mac only: Audio Mode plays on the Mac; it is set there. */
  "audio.preview": { class: 'mac_only'; params: unknown; result: unknown };
  /** Use a private folder of cues in place. The Mac only: It names a folder on the Mac. */
  "audio.import_commander": { class: 'mac_only'; params: unknown; result: unknown };
  /** Online or offline, and whether Continuity is on. */
  "connection.status": { class: 'read'; params: Record<string, never>; result: unknown };
  /** Continuity's state: connection, local model, waits and handoffs. */
  "continuity.status": { class: 'read'; params: Record<string, never>; result: unknown };
  /** Local models and whether each fits this Mac's memory. */
  "local.models": { class: 'read'; params: Record<string, never>; result: unknown };
  /** What is installed locally: Ollama, OpenCode, models. */
  "local.inventory": { class: 'read'; params: Record<string, never>; result: unknown };
  /** The local models Continuity may use. */
  "local.catalogue": { class: 'read'; params: Record<string, never>; result: unknown };
  /** Local model downloads in progress. */
  "local.downloads": { class: 'read'; params: Record<string, never>; result: unknown };
  /** Agents moved to another provider or to local, and back. */
  "continuity.handoffs": { class: 'read'; params: Record<string, never>; result: unknown };
  /** Agents waiting for a provider to come back. */
  "continuity.waits": { class: 'read'; params: Record<string, never>; result: unknown };
  /** Where an agent can be moved to (local, back, a provider). */
  "run.targets": { class: 'read'; params: {
    run_id: string;
  }; result: unknown };
  /** Whether Ollama is installed and running. */
  "ollama.status": { class: 'read'; params: Record<string, never>; result: unknown };
  /** Check the connection now. */
  "connection.check": { class: 'control'; params: Record<string, never>; result: unknown };
  /** Move an agent to local, back, or another provider. */
  "run.handoff": { class: 'control'; params: {
    run_id: string;
    to: string;
    accept_mode?: string | null;
  }; result: unknown };
  /** Retry a waiting agent now. */
  "run.retry_now": { class: 'control'; params: {
    run_id: string;
  }; result: unknown };
  /** Keep an agent where it is instead of moving it. */
  "run.stay": { class: 'control'; params: {
    run_id: string;
  }; result: unknown };
  /** Continuity settings. The Mac only: Continuity is set on the Mac. */
  "settings.get": { class: 'mac_only'; params: unknown; result: unknown };
  /** Change Continuity settings. The Mac only: Continuity is set on the Mac. */
  "settings.set": { class: 'mac_only'; params: unknown; result: unknown };
  /** The first-use notice's state in VS Code. The Mac only: It describes the Mac's own windows. */
  "continuity.ui": { class: 'mac_only'; params: unknown; result: unknown };
  /** Dismiss the first-use notice. The Mac only: It describes the Mac's own windows. */
  "continuity.notice": { class: 'mac_only'; params: unknown; result: unknown };
  /** Offer to download a local model ahead of time. The Mac only: It changes what runs on the Mac and how much of its memory is used. */
  "continuity.prefetch_offer": { class: 'mac_only'; params: unknown; result: unknown };
  /** Choose the local model. The Mac only: It changes what runs on the Mac and how much of its memory is used. */
  "local.pick": { class: 'mac_only'; params: unknown; result: unknown };
  /** Approve a local model download. The Mac only: It changes what runs on the Mac and how much of its memory is used. */
  "local.approve": { class: 'mac_only'; params: unknown; result: unknown };
  /** Load a local model into memory. The Mac only: It changes what runs on the Mac and how much of its memory is used. */
  "local.load": { class: 'mac_only'; params: unknown; result: unknown };
  /** Unload a local model. The Mac only: It changes what runs on the Mac and how much of its memory is used. */
  "local.unload": { class: 'mac_only'; params: unknown; result: unknown };
  /** Download a local model. The Mac only: It changes what runs on the Mac and how much of its memory is used. */
  "local.pull": { class: 'mac_only'; params: unknown; result: unknown };
  /** Cancel a local model download. The Mac only: It changes what runs on the Mac and how much of its memory is used. */
  "local.pull_cancel": { class: 'mac_only'; params: unknown; result: unknown };
  /** Install Ollama. The Mac only: It changes what runs on the Mac and how much of its memory is used. */
  "ollama.install": { class: 'mac_only'; params: unknown; result: unknown };
  /** Start Ollama. The Mac only: It changes what runs on the Mac and how much of its memory is used. */
  "ollama.start": { class: 'mac_only'; params: unknown; result: unknown };
  /** Stop Ollama. The Mac only: It changes what runs on the Mac and how much of its memory is used. */
  "ollama.stop": { class: 'mac_only'; params: unknown; result: unknown };
  /** Age a wait (tests only). The Mac only: A test hook. */
  "continuity.test_age": { class: 'mac_only'; params: unknown; result: unknown };
  /** Every agent, as Overseer sees them. */
  "agents.roster": { class: 'mac_only'; params: unknown; result: unknown };
  /** A digest of what an agent did. */
  "agent.digest": { class: 'mac_only'; params: unknown; result: unknown };
  /** Set or read the area an agent works in. */
  "agent.area": { class: 'mac_only'; params: unknown; result: unknown };
  /** The briefings an agent was given. */
  "agent.briefings": { class: 'mac_only'; params: unknown; result: unknown };
  /** Set how often an agent checks in. */
  "agent.cadence": { class: 'mac_only'; params: unknown; result: unknown };
  /** Turn briefings and the channel on or off. */
  "agent.channel": { class: 'mac_only'; params: unknown; result: unknown };
  /** An agent's check-ins. */
  "agent.check_ins": { class: 'mac_only'; params: unknown; result: unknown };
  /** Add a guardrail to an agent. */
  "agent.guardrail": { class: 'mac_only'; params: unknown; result: unknown };
  /** Remove a guardrail. */
  "agent.guardrail_remove": { class: 'mac_only'; params: unknown; result: unknown };
  /** An agent's guardrails. */
  "agent.guardrails": { class: 'mac_only'; params: unknown; result: unknown };
  /** Hold an agent. */
  "agent.hold": { class: 'mac_only'; params: unknown; result: unknown };
  /** The agents on hold. */
  "agent.holds": { class: 'mac_only'; params: unknown; result: unknown };
  /** Release a held agent. */
  "agent.release": { class: 'mac_only'; params: unknown; result: unknown };
  /** Redirect an agent. */
  "agent.redirect": { class: 'mac_only'; params: unknown; result: unknown };
  /** Refuse shares to an agent. */
  "agent.share_deny": { class: 'mac_only'; params: unknown; result: unknown };
  /** Redirect an agent. */
  "run.redirect": { class: 'mac_only'; params: unknown; result: unknown };
  /** Queue a message for an agent. */
  "run.queue": { class: 'mac_only'; params: unknown; result: unknown };
  /** An agent's queued messages. */
  "run.queued": { class: 'mac_only'; params: unknown; result: unknown };
  /** Remove a queued message. */
  "run.unqueue": { class: 'mac_only'; params: unknown; result: unknown };
  /** The agents' channel. */
  "channel.messages": { class: 'mac_only'; params: unknown; result: unknown };
  /** Conflicts between agents. */
  "conflicts.list": { class: 'mac_only'; params: unknown; result: unknown };
  /** Dismiss a conflict between agents. */
  "conflict.dismiss": { class: 'mac_only'; params: unknown; result: unknown };
  /** Resolve a conflict between agents. */
  "conflict.resolve": { class: 'mac_only'; params: unknown; result: unknown };
  /** What agents shared. */
  "share.list": { class: 'mac_only'; params: unknown; result: unknown };
  /** Withdraw a share. */
  "share.withdraw": { class: 'mac_only'; params: unknown; result: unknown };
  /** Start a watch on an agent. */
  "watch.start": { class: 'mac_only'; params: unknown; result: unknown };
  /** End a watch. */
  "watch.end": { class: 'mac_only'; params: unknown; result: unknown };
  /** The watches. */
  "watch.list": { class: 'mac_only'; params: unknown; result: unknown };
  /** What a watch found. */
  "watch.findings": { class: 'mac_only'; params: unknown; result: unknown };
  /** Overseer's session. */
  "overseer.session": { class: 'mac_only'; params: unknown; result: unknown };
  /** The conversation with Overseer. */
  "overseer.messages": { class: 'mac_only'; params: unknown; result: unknown };
  /** Say something to Overseer. */
  "overseer.send": { class: 'mac_only'; params: unknown; result: unknown };
  /** Propose actions for the owner to approve. */
  "overseer.propose": { class: 'mac_only'; params: unknown; result: unknown };
  /** Answer one of Overseer's proposals. */
  "overseer.answer": { class: 'mac_only'; params: unknown; result: unknown };
  /** Cancel one of Overseer's proposals. */
  "overseer.cancel": { class: 'mac_only'; params: unknown; result: unknown };
  /** One of Overseer's cards. */
  "overseer.card": { class: 'mac_only'; params: unknown; result: unknown };
  /** Set how much Overseer does on its own. */
  "overseer.level": { class: 'mac_only'; params: unknown; result: unknown };
  /** Set Overseer's spending cap. */
  "overseer.cap": { class: 'mac_only'; params: unknown; result: unknown };
  /** Start a fresh Overseer conversation. */
  "overseer.fresh": { class: 'mac_only'; params: unknown; result: unknown };
  /** Rally the agents. */
  "overseer.rally": { class: 'mac_only'; params: unknown; result: unknown };
  /** Scan an agent for conflicts. */
  "overseer.scan": { class: 'mac_only'; params: unknown; result: unknown };
  /** A token for an agent's Overseer tools. The Mac only: It is for the agents' own Overseer tools, never a phone. */
  "overseer.token": { class: 'mac_only'; params: unknown; result: unknown };
  /** The Overseer tools an agent may use. The Mac only: It is for the agents' own Overseer tools, never a phone. */
  "overseer.tools": { class: 'mac_only'; params: unknown; result: unknown };
  /** Run one of Overseer's tools for an agent. The Mac only: It is for the agents' own Overseer tools, never a phone. */
  "overseer.tool": { class: 'mac_only'; params: unknown; result: unknown };
  /** Voice Mode's settings. The Mac only: Voice Mode (Gate R) listens and speaks on the Mac; the phone remote has no voice, as the owner chose. */
  "voice.get": { class: 'mac_only'; params: unknown; result: unknown };
  /** Change Voice Mode's settings. The Mac only: Voice Mode (Gate R) listens and speaks on the Mac; the phone remote has no voice, as the owner chose. */
  "voice.set": { class: 'mac_only'; params: unknown; result: unknown };
  /** Which agent Voice Mode speaks for. The Mac only: Voice Mode (Gate R) listens and speaks on the Mac; the phone remote has no voice, as the owner chose. */
  "voice.focus": { class: 'mac_only'; params: unknown; result: unknown };
  /** Say something to Voice Mode. The Mac only: Voice Mode (Gate R) listens and speaks on the Mac; the phone remote has no voice, as the owner chose. */
  "voice.say": { class: 'mac_only'; params: unknown; result: unknown };
  /** Speak a text aloud on the Mac. The Mac only: Voice Mode (Gate R) listens and speaks on the Mac; the phone remote has no voice, as the owner chose. */
  "voice.speak": { class: 'mac_only'; params: unknown; result: unknown };
  /** Read an agent's answer aloud on the Mac. The Mac only: Voice Mode (Gate R) listens and speaks on the Mac; the phone remote has no voice, as the owner chose. */
  "voice.read_back": { class: 'mac_only'; params: unknown; result: unknown };
  /** Answer by voice. The Mac only: Voice Mode (Gate R) listens and speaks on the Mac; the phone remote has no voice, as the owner chose. */
  "voice.answer": { class: 'mac_only'; params: unknown; result: unknown };
  /** Stop what Voice Mode is doing. The Mac only: Voice Mode (Gate R) listens and speaks on the Mac; the phone remote has no voice, as the owner chose. */
  "voice.cancel": { class: 'mac_only'; params: unknown; result: unknown };
  /** What Voice Mode is waiting to hear. The Mac only: Voice Mode (Gate R) listens and speaks on the Mac; the phone remote has no voice, as the owner chose. */
  "voice.requests": { class: 'mac_only'; params: unknown; result: unknown };
  /** Download a voice. The Mac only: Voice Mode (Gate R) listens and speaks on the Mac; the phone remote has no voice, as the owner chose. */
  "voice.download": { class: 'mac_only'; params: unknown; result: unknown };
  /** Simulate speech for tests. The Mac only: Voice Mode (Gate R) listens and speaks on the Mac; the phone remote has no voice, as the owner chose. */
  "voice.simulate": { class: 'mac_only'; params: unknown; result: unknown };
}

export type MethodName = keyof Methods;

/** Methods a phone may call, by what they need. A control method carries a request id. */
export const METHOD_CLASS = {
  "hello": 'self',
  "ping": 'self',
  "events.subscribe": 'self',
  "device.notifications": 'self',
  "state": 'read',
  "harness.list": 'read',
  "profile.list": 'read',
  "profile.status": 'read',
  "repo.inspect": 'read',
  "repo.known": 'read',
  "repo.files": 'read',
  "run.raw_output": 'read',
  "run.turns": 'read',
  "run.active": 'read',
  "events.list": 'read',
  "comparison.options": 'read',
  "workspace.diff": 'read',
  "workspace.status": 'read',
  "workspace.changes": 'read',
  "workspace.tree": 'read',
  "workspace.file": 'read',
  "workspace.hunks": 'read',
  "workspace.cleanup_plan": 'read',
  "workspace.pr_plan": 'read',
  "workspace.merge_plan": 'read',
  "review.marks": 'read',
  "account.list": 'read',
  "account.usage": 'read',
  "search": 'read',
  "daemon.last_notice": 'read',
  "daemon.clients": 'read',
  "task.create": 'control',
  "task.archive": 'control',
  "run.follow_up": 'control',
  "run.interrupt": 'control',
  "run.permission": 'control',
  "runs.stop_all": 'control',
  "workspace.cleanup": 'control',
  "workspace.pr_prepare": 'control',
  "workspace.pr_open": 'control',
  "workspace.pr_opened": 'control',
  "workspace.merge_prepare": 'control',
  "workspace.merge_resolved": 'control',
  "workspace.merge_complete": 'control',
  "workspace.merge_abort": 'control',
  "review.accept": 'control',
  "review.unaccept": 'control',
  "review.import": 'control',
  "review.reject": 'control',
  "profile.create": 'control',
  "profile.rename": 'control',
  "profile.logout": 'control',
  "profile.device_login": 'control',
  "account.create": 'control',
  "account.remove": 'control',
  "daemon.shutdown": 'mac_only',
  "daemon.stop_all": 'mac_only',
  "daemon.background_notice": 'mac_only',
  "daemon.test_notice": 'mac_only',
  "profile.login_command": 'mac_only',
  "gateway.status": 'mac_only',
  "gateway.enable": 'mac_only',
  "gateway.disable": 'mac_only',
  "gateway.settings": 'mac_only',
  "gateway.pair_start": 'mac_only',
  "gateway.pair_cancel": 'mac_only',
  "gateway.pair_confirm": 'mac_only',
  "gateway.devices": 'mac_only',
  "gateway.device_revoke": 'mac_only',
  "gateway.device_scope": 'mac_only',
  "gateway.device_rename": 'mac_only',
  "ui.focus": 'mac_only',
  "audio.get": 'read',
  "audio.voices": 'read',
  "audio.set": 'mac_only',
  "audio.preview": 'mac_only',
  "audio.import_commander": 'mac_only',
  "connection.status": 'read',
  "continuity.status": 'read',
  "local.models": 'read',
  "local.inventory": 'read',
  "local.catalogue": 'read',
  "local.downloads": 'read',
  "continuity.handoffs": 'read',
  "continuity.waits": 'read',
  "run.targets": 'read',
  "ollama.status": 'read',
  "connection.check": 'control',
  "run.handoff": 'control',
  "run.retry_now": 'control',
  "run.stay": 'control',
  "settings.get": 'mac_only',
  "settings.set": 'mac_only',
  "continuity.ui": 'mac_only',
  "continuity.notice": 'mac_only',
  "continuity.prefetch_offer": 'mac_only',
  "local.pick": 'mac_only',
  "local.approve": 'mac_only',
  "local.load": 'mac_only',
  "local.unload": 'mac_only',
  "local.pull": 'mac_only',
  "local.pull_cancel": 'mac_only',
  "ollama.install": 'mac_only',
  "ollama.start": 'mac_only',
  "ollama.stop": 'mac_only',
  "continuity.test_age": 'mac_only',
  "agents.roster": 'mac_only',
  "agent.digest": 'mac_only',
  "agent.area": 'mac_only',
  "agent.briefings": 'mac_only',
  "agent.cadence": 'mac_only',
  "agent.channel": 'mac_only',
  "agent.check_ins": 'mac_only',
  "agent.guardrail": 'mac_only',
  "agent.guardrail_remove": 'mac_only',
  "agent.guardrails": 'mac_only',
  "agent.hold": 'mac_only',
  "agent.holds": 'mac_only',
  "agent.release": 'mac_only',
  "agent.redirect": 'mac_only',
  "agent.share_deny": 'mac_only',
  "run.redirect": 'mac_only',
  "run.queue": 'mac_only',
  "run.queued": 'mac_only',
  "run.unqueue": 'mac_only',
  "channel.messages": 'mac_only',
  "conflicts.list": 'mac_only',
  "conflict.dismiss": 'mac_only',
  "conflict.resolve": 'mac_only',
  "share.list": 'mac_only',
  "share.withdraw": 'mac_only',
  "watch.start": 'mac_only',
  "watch.end": 'mac_only',
  "watch.list": 'mac_only',
  "watch.findings": 'mac_only',
  "overseer.session": 'mac_only',
  "overseer.messages": 'mac_only',
  "overseer.send": 'mac_only',
  "overseer.propose": 'mac_only',
  "overseer.answer": 'mac_only',
  "overseer.cancel": 'mac_only',
  "overseer.card": 'mac_only',
  "overseer.level": 'mac_only',
  "overseer.cap": 'mac_only',
  "overseer.fresh": 'mac_only',
  "overseer.rally": 'mac_only',
  "overseer.scan": 'mac_only',
  "overseer.token": 'mac_only',
  "overseer.tools": 'mac_only',
  "overseer.tool": 'mac_only',
  "voice.get": 'mac_only',
  "voice.set": 'mac_only',
  "voice.focus": 'mac_only',
  "voice.say": 'mac_only',
  "voice.speak": 'mac_only',
  "voice.read_back": 'mac_only',
  "voice.answer": 'mac_only',
  "voice.cancel": 'mac_only',
  "voice.requests": 'mac_only',
  "voice.download": 'mac_only',
  "voice.simulate": 'mac_only',
} as const satisfies Record<MethodName, MethodClass>;

export type PhoneMethod = { [K in MethodName]: Methods[K]['class'] extends 'mac_only' ? never : K }[MethodName];
export type ControlMethod = { [K in MethodName]: Methods[K]['class'] extends 'control' ? K : never }[MethodName];
export type Params<M extends MethodName> = Methods[M]['params'];
export type Result<M extends MethodName> = Methods[M]['result'];
