// Generated by protocol/gen-ts.mjs from protocol/protocol.json. Do not edit: change the
// description and run `node protocol/gen-ts.mjs`. `--check` fails when this file is not current.

export const PROTOCOL_VERSION = 1 as const;

export type RunStatus = 'queued' | 'starting' | 'running' | 'waiting_for_user' | 'completed' | 'failed' | 'interrupted' | 'disconnected' | 'unknown';

export type Scope = 'full' | 'watch';

export interface Task {
  id: string;
  title: string;
  prompt: string;
  repo_root: string;
  target_ref?: string | null;
  workspace_id: string;
  start_snapshot?: string | null;
  fork_commit?: string | null;
  fork_provenance?: string | null;
  created_ms: number;
  archived_ms?: number | null;
}

export interface Workspace {
  id: string;
  path: string;
  repo_root: string;
  common_dir: string;
  kind: 'worktree' | 'current';
  branch?: string | null;
  owner_run_id?: string | null;
  initial_dirty: unknown;
  created_ms: number;
  removed_ms?: number | null;
}

export interface Attention {
  kind: string;
  request_id: string;
  tool?: string | null;
  input: unknown;
}

export interface Run {
  id: string;
  task_id: string;
  parent_run_id?: string | null;
  harness: string;
  harness_version?: string | null;
  profile_id?: string | null;
  model?: string | null;
  effort?: string | null;
  workspace_id: string;
  native_id?: string | null;
  status: RunStatus;
  exit_reason?: string | null;
  plain_reason?: string | null;
  created_ms: number;
  ended_ms?: number | null;
  title: string;
  relation_source?: string | null;
  relation_confidence?: string | null;
  capabilities: unknown;
  process_generation: number;
  attention?: Attention | null;
  queue?: QueueSnapshot | null;
}

export interface Turn {
  id: string;
  run_id: string;
  n: number;
  prompt: string;
  snapshot_id?: string | null;
  started_ms: number;
  ended_ms?: number | null;
  status: string;
}

export interface Account {
  provider: string;
  plan?: string | null;
  email?: string | null;
  default: boolean;
  name: string;
  label: string;
  short: string;
}

export interface Profile {
  id: string;
  name: string;
  harness: string;
  home?: string | null;
  is_system: boolean;
  created_ms: number;
  account?: Account | null;
}

export interface Event {
  seq: number;
  ts: number;
  task_id?: string | null;
  run_id?: string | null;
  kind: string;
  source: string;
  confidence: string;
  payload: unknown;
}

export interface Change {
  status: string;
  path: string;
  old_path?: string | null;
}

export interface GitStatus {
  branch?: string | null;
  head?: string | null;
  staged: Array<Change>;
  unstaged: Array<Change>;
  untracked: Array<string>;
  conflicted: Array<string>;
}

export interface State {
  cursor: number;
  tasks: Array<Task>;
  runs: Array<Run>;
  workspaces: Array<Workspace>;
  profiles: Array<Profile>;
  turns: Record<string, Array<Turn>>;
  oversight: Record<string, unknown>;
  overseer: unknown;
  landings: Record<string, unknown>;
  reviewed?: Record<string, number> | null;
  daemon: {
    pid: number;
    started_ms: number;
    version: string;
    parser_version: string;
    swarm_storage: 'blocked' | 'ready';
  };
}

export interface Harness {
  harness: string;
  program?: string | null;
  version?: string | null;
  installed: boolean;
  capabilities: unknown;
}

export interface Comparison {
  mode: string;
  label: string;
  base?: string | null;
  available: boolean;
  default?: boolean | null;
  detail?: string | null;
  inherited?: boolean | null;
  provenance?: string | null;
  branch?: string | null;
  snapshot?: unknown | null;
}

export interface FileSide {
  exists: boolean;
  size: number;
  kind: 'text' | 'missing' | 'binary' | 'too_large' | 'link' | 'directory' | 'special';
  text?: string | null;
  note?: string | null;
}

export interface Hunk {
  key: string;
  base_start: number;
  base_lines: Array<string>;
  modified_start: number;
  modified_lines: Array<string>;
  reviewed: boolean;
}

export interface Mark {
  key: string;
  path: string;
  at_ms: number;
  by: string;
}

export interface TreeEntry {
  name?: string | null;
  path: string;
  dir: boolean;
  symlink?: boolean | null;
  status?: string | null;
  changes_inside: number;
  deleted?: boolean | null;
}

export interface NotificationSettings {
  enabled: boolean;
  kinds: {
    permission: boolean;
    question: boolean;
    failure: boolean;
    finished: boolean;
  };
  show_text: boolean;
  token?: string | null;
  environment: string;
  bundle?: string | null;
}

export interface KnownRepo {
  root: string;
  name: string;
  last_used_ms: number;
  exists: boolean;
  branch?: string | null;
  default_branch?: string | null;
}

export interface VoiceCapturedTurn {
  id: string;
  requests: Array<string>;
  asked_again: boolean;
  started_seq: number;
  cause: string;
}

export interface QueuedMessage {
  id: number;
  ts: number;
  source: string;
  text: string;
  redirect: boolean;
}

export interface QueueSnapshot {
  paused: boolean;
  messages: Array<QueuedMessage>;
}

export interface QueuedDelivery {
  delivery: 'queued';
}

export type FollowUpResult = Turn | QueuedDelivery;

export interface NativeSessionGrant {
  v: number;
  harness: 'claude' | 'codex-app';
  family: 'can_use_tool' | 'item/commandExecution/requestApproval';
  scope: 'session';
  digest: string;
  host_replay_qualified: boolean;
}

export interface ModScope {
  kind: 'all_agents' | 'repository' | 'watchers' | 'agent' | 'overseer';
  repo_key?: string | null;
  run_id?: string | null;
}

export interface ModFilters {
  harnesses: Array<string>;
  accounts: Array<string>;
  models: Array<string>;
}

export interface ModBindingInput {
  id?: string | null;
  mod_id: string;
  version: string;
  fingerprint: string;
  scope: ModScope;
  enabled: boolean;
  required?: boolean | null;
  locked?: boolean | null;
  filters?: ModFilters | null;
}

export interface ModBinding {
  id: string;
  mod_id: string;
  version: string;
  fingerprint: string;
  scope: ModScope;
  enabled: boolean;
  required: boolean;
  locked: boolean;
  filters: ModFilters;
  changed_ms: number;
  actor: string;
}

export interface ModVersion {
  id: string;
  version: string;
  fingerprint: string;
  manifest: unknown;
  source: string;
  installed_ms: number;
  files: Array<unknown>;
}

export interface ModContext {
  run_id: string;
  role: string;
  repo_key: string;
  harness: string;
  harness_version?: string | null;
  account_id?: string | null;
  model?: string | null;
  native_thread_exists: boolean;
  local_model_selection: boolean;
}

export interface ModDecision {
  binding_id: string;
  mod_id: string;
  fingerprint: string;
  status: 'selected' | 'disabled' | 'overridden' | 'filtered' | 'not_in_scope' | 'unqualified';
  reason: string;
  required: boolean;
  delivery: 'unsupported' | 'message_text' | 'native_instructions';
  activation: 'next_turn' | 'next_thread';
  children: 'yes' | 'no' | 'unknown';
}

export interface ModPlan {
  revision: number;
  versions: Array<ModVersion>;
  rules_text: string;
  style_text: string;
  decisions: Array<ModDecision>;
}

export interface AppliedMods {
  context: ModContext;
  desired: ModPlan;
  last_turn?: TurnModSnapshot | null;
  pending: boolean;
  support: unknown;
  notice: string;
}

export interface TurnModSnapshot {
  turn_id: string;
  run_id: string;
  plan: ModPlan;
  context: ModContext;
  binding_snapshot: Array<ModBinding>;
  delivery: 'none' | 'unsupported' | 'message_text';
  transport: string;
  activation: 'next_turn';
  children: 'unknown';
  text: string;
  digest: string;
  added_bytes: number;
  applied_fingerprints: Array<string>;
  outcome: 'prepared' | 'transport_accepted' | 'failed_before_effect' | 'uncertain_after_effect';
  outcome_ms: number;
  outcome_detail?: string | null;
  planned_fingerprints: Array<string>;
  text_redacted: boolean;
}

/** The payload of every kind of event the app reads. Other kinds arrive as `unknown`. */
export interface EventPayloads {
  task_created: {
    task: Task;
    run: Run;
    workspace: Workspace;
  };
  task_archived: {
    archived: boolean;
  };
  turn_started: {
    turn: Turn;
    snapshot?: string | null;
  };
  turn_done: {
    ok: boolean;
    summary?: string | null;
  };
  status: {
    status: RunStatus;
    reason?: string | null;
    why?: string | null;
    evidence?: unknown | null;
    generation?: number | null;
    program?: string | null;
  };
  session: {
    native_id: string;
  };
  output: {
    role: string;
    text: string;
  };
  tool: {
    id?: string | null;
    name: string;
    summary?: string | null;
  };
  tool_result: {
    id?: string | null;
    input?: unknown | null;
    is_error?: boolean | null;
    output?: unknown | null;
    status?: string | null;
  };
  file_activity: {
    paths: Array<string>;
    kind: string;
    attribution: string;
  };
  permission: Attention;
  permission_answered: {
    request_id: string;
    allow: boolean;
    by?: string | null;
    always?: string | null;
    grant?: NativeSessionGrant | null;
  };
  usage: unknown;
  error: {
    class: string;
    message: string;
    request?: unknown | null;
  };
  retention: unknown;
  review_seen: {
    marks: Record<string, number>;
  };
  review_mark: {
    key: string;
    path: string;
    reviewed: boolean;
  };
  review_reject: {
    path: string;
    key: string;
    base: string;
    lines_restored: number;
    lines_removed: number;
    file_removed: boolean;
  };
  pull_request: {
    url: string;
    number: number;
    branch?: string | null;
  };
  remote_command: {
    method: string;
    device: string;
    request_id?: string | null;
  };
  gateway_state: {
    state: 'on' | 'off';
    port?: number | null;
    fingerprint?: string | null;
    closed?: number | null;
  };
  gateway_sessions: {
    sessions: number;
    device: string;
    name: string;
    change: 'connected' | 'disconnected';
  };
  power: {
    awake: boolean;
    why: string;
    runs?: Array<string> | null;
  };
  push: {
    device: string;
    name: string;
    kind: string;
    route: string;
    outcome: 'sent' | 'not_sent';
    why: string;
    fields: Array<string>;
  };
  profile: unknown;
  child: {
    child: Run;
    evidence: unknown;
    workspace: string;
  };
  child_reparented: {
    child_run_id: string;
    parent_run_id: string;
  };
  raw_unparsed: {
    text: string;
    parser_version: string;
  };
  connection: {
    status: unknown;
    previous: unknown;
    first?: boolean | null;
  };
  trouble: {
    kind: string;
    reason: string;
  };
  overseer_turn_processed: {
    turn: VoiceCapturedTurn;
    status: string;
    source_seq: number;
  };
  overseer_message: {
    session: string;
    message: unknown;
    turn?: VoiceCapturedTurn | null;
  };
  queue_changed: {
    paused?: boolean | null;
    removed?: number | null;
    id?: number | null;
    delivered?: number | null;
  };
  queued: {
    text: string;
    detail: unknown;
    paused?: boolean | null;
  };
  mods_changed: {
    operation: string;
    binding?: ModBinding | null;
    binding_id?: string | null;
    mod_id?: string | null;
    fingerprint?: string | null;
    revision: number;
    ended_bindings?: Array<string> | null;
  };
  mods_applied: {
    snapshot: TurnModSnapshot;
  };
}

export type KnownEventKind = keyof EventPayloads;

/** An event whose payload is typed by its kind. */
export type TypedEvent = { [K in KnownEventKind]: Omit<Event, 'kind' | 'payload'> & { kind: K; payload: EventPayloads[K] } }[KnownEventKind];

export type MethodClass = 'self' | 'read' | 'control' | 'mac_only';

/** Every method of the daemon: its class for a phone, its parameters and its result. */
export interface Methods {
  /** Say who is connecting; returns protocol, version and, for a device, its scope. */
  "hello": { class: 'self'; params: {
    client?: string | null;
  }; result: unknown };
  /** Keep the session alive; returns the daemon's time. */
  "ping": { class: 'self'; params: Record<string, never>; result: {
    now_ms: number;
  } };
  /** Replay events after a cursor, then stream live events. */
  "events.subscribe": { class: 'self'; params: {
    after?: number | null;
    run_id?: string | null;
  }; result: {
    subscribed: boolean;
    after: number;
    history_truncated: boolean;
  } };
  /** Read or change this device's notification switches and push token. */
  "device.notifications": { class: 'self'; params: {
    enabled?: boolean | null;
    show_text?: boolean | null;
    kinds?: unknown | null;
    token?: string | null;
    environment?: string | null;
    bundle?: string | null;
  }; result: NotificationSettings };
  /** Every task, run, workspace and account profile. */
  "state": { class: 'read'; params: Record<string, never>; result: State };
  /** Installed harnesses with versions and capabilities. */
  "harness.list": { class: 'read'; params: Record<string, never>; result: Array<Harness> };
  /** Account profiles. */
  "profile.list": { class: 'read'; params: Record<string, never>; result: Array<Profile> };
  /** Sign-in state of one account profile. */
  "profile.status": { class: 'read'; params: {
    id: string;
  }; result: {
    profile_id: string;
    installed: boolean;
    logged_in: boolean;
    program?: string | null;
    version?: string | null;
    method?: string | null;
    identity?: unknown | null;
    detail?: string | null;
    account?: unknown | null;
    expires_ms?: number | null;
    note?: string | null;
  } };
  /** Branches, head and status of a repository Overseer knows. */
  "repo.inspect": { class: 'read'; params: {
    path: string;
  }; result: {
    root: string;
    head?: string | null;
    branch?: string | null;
    default_branch?: string | null;
    branches: Array<string>;
    status: GitStatus;
  } };
  /** The repositories Overseer has used. */
  "repo.known": { class: 'read'; params: Record<string, never>; result: {
    repos: Array<KnownRepo>;
  } };
  /** Files of a worktree or repository, for mentions. */
  "repo.files": { class: 'read'; params: {
    workspace_id?: string | null;
    repo?: string | null;
    query?: string | null;
    limit?: number | null;
  }; result: {
    root: string;
    files: Array<string>;
  } };
  /** The end of a run's raw output. */
  "run.raw_output": { class: 'read'; params: {
    run_id: string;
    max_bytes?: number | null;
  }; result: {
    lines: Array<unknown>;
    truncated: boolean;
    note?: string | null;
  } };
  /** The turns of a run. */
  "run.turns": { class: 'read'; params: {
    run_id: string;
  }; result: Array<Turn> };
  /** Runs that are active now. */
  "run.active": { class: 'read'; params: Record<string, never>; result: Array<Run> };
  /** A page of events. */
  "events.list": { class: 'read'; params: {
    run_id?: string | null;
    after?: number | null;
    limit?: number | null;
  }; result: {
    events: Array<Event>;
    oldest_retained?: number | null;
  } };
  /** The comparisons a run offers. */
  "comparison.options": { class: 'read'; params: {
    run_id: string;
    branch?: string | null;
  }; result: {
    run_id: string;
    workspace: Workspace;
    head?: string | null;
    branch?: string | null;
    branches: Array<string>;
    options: Array<Comparison>;
    folder_edits: boolean;
  } };
  /** The diff of a workspace against a comparison. */
  "workspace.diff": { class: 'read'; params: {
    workspace_id: string;
    base: string;
    status?: boolean | null;
  }; result: {
    workspace_id: string;
    root: string;
    base: string;
    current_tree: string;
    index_tree: string;
    head?: string | null;
    changes: Array<Change>;
    status?: GitStatus | null;
  } };
  /** Git status of a workspace. */
  "workspace.status": { class: 'read'; params: {
    workspace_id: string;
  }; result: GitStatus };
  /** Changed files of a workspace since the task started. */
  "workspace.changes": { class: 'read'; params: {
    workspace_id: string;
  }; result: {
    files: number;
    added: number;
    removed: number;
    names: Array<string>;
    base?: string | null;
  } };
  /** One directory of a worktree. */
  "workspace.tree": { class: 'read'; params: {
    workspace_id: string;
    dir?: string | null;
  }; result: {
    workspace_id: string;
    root: string;
    dir: string;
    base?: string | null;
    entries: Array<TreeEntry>;
    total: number;
    truncated: boolean;
    changed_total: number;
  } };
  /** One file of a workspace, at a comparison and in the working copy. */
  "workspace.file": { class: 'read'; params: {
    workspace_id: string;
    path: string;
    base?: string | null;
  }; result: {
    workspace_id: string;
    path: string;
    base?: string | null;
    before: FileSide;
    now: FileSide;
  } };
  /** The changes of one file as hunks, with their keys and reviewed marks. */
  "workspace.hunks": { class: 'read'; params: {
    workspace_id: string;
    path: string;
    base: string;
    run_id?: string | null;
  }; result: {
    workspace_id: string;
    path: string;
    base: string;
    shown: boolean;
    why?: string | null;
    hunks: Array<Hunk>;
    before: {
      exists: boolean;
      kind: string;
      lines?: number | null;
    };
    now: {
      exists: boolean;
      kind: string;
      lines?: number | null;
    };
  } };
  /** What cleaning up a worktree would remove. */
  "workspace.cleanup_plan": { class: 'read'; params: {
    workspace_id: string;
  }; result: {
    workspace: Workspace;
    active_runs: Array<unknown>;
    dirty?: GitStatus | null;
    removable: boolean;
    reason: string;
  } };
  /** What opening a pull request would do. */
  "workspace.pr_plan": { class: 'read'; params: {
    workspace_id: string;
  }; result: unknown };
  /** What merging back would do. */
  "workspace.merge_plan": { class: 'read'; params: {
    workspace_id: string;
  }; result: unknown };
  /** The hunks marked reviewed for a run. */
  "review.marks": { class: 'read'; params: {
    run_id: string;
  }; result: {
    run_id: string;
    keys: Array<string>;
    marks: Array<Mark>;
  } };
  /** Accounts with sign-in state and plan. */
  "account.list": { class: 'read'; params: Record<string, never>; result: {
    accounts: Array<unknown>;
    providers: Array<unknown>;
  } };
  /** Usage and limits of one account. */
  "account.usage": { class: 'read'; params: {
    id: string;
  }; result: unknown };
  /** Search tasks and runs. */
  "search": { class: 'read'; params: {
    query?: string | null;
    limit?: number | null;
  }; result: {
    task_ids: Array<string>;
    ms: number;
  } };
  /** The last background notice. */
  "daemon.last_notice": { class: 'read'; params: Record<string, never>; result: {
    notice?: unknown | null;
  } };
  /** How many watching UIs are connected. */
  "daemon.clients": { class: 'read'; params: Record<string, never>; result: {
    vscode: number;
    ui: number;
  } };
  /** Start an agent. */
  "task.create": { class: 'control'; params: {
    repo: string;
    harness: string;
    prompt: string;
    title?: string | null;
    workspace_mode?: 'worktree' | 'current' | null;
    profile_id?: string | null;
    target_ref?: string | null;
    model?: string | null;
    effort?: string | null;
    permission_mode?: string | null;
    images?: Array<unknown> | null;
  }; result: {
    task: Task;
    run: Run;
    workspace: Workspace;
  } };
  /** Archive or restore a task. */
  "task.archive": { class: 'control'; params: {
    task_id: string;
    archived?: boolean | null;
  }; result: {
    task_id: string;
    archived_ms?: number | null;
  } };
  /** Send a message to an agent. */
  "run.follow_up": { class: 'control'; params: {
    run_id: string;
    prompt: string;
    model?: string | null;
    effort?: string | null;
    permission_mode?: string | null;
    images?: Array<unknown> | null;
  }; result: FollowUpResult };
  /** Stop an agent's turn. */
  "run.interrupt": { class: 'control'; params: {
    run_id: string;
  }; result: unknown };
  /** Allow or deny a permission request. */
  "run.permission": { class: 'control'; params: {
    run_id: string;
    request_id: string;
    allow: boolean;
    message?: string | null;
  }; result: {
    ok: boolean;
  } };
  /** Stop every active agent; the daemon keeps running. */
  "runs.stop_all": { class: 'control'; params: Record<string, never>; result: {
    interrupted: Array<string>;
    failed: Array<unknown>;
  } };
  /** Remove a finished agent's worktree. */
  "workspace.cleanup": { class: 'control'; params: {
    workspace_id: string;
    discard_dirty?: boolean | null;
  }; result: unknown };
  /** Commit and prepare the branch for a pull request. */
  "workspace.pr_prepare": { class: 'control'; params: {
    workspace_id: string;
  }; result: unknown };
  /** Open the pull request with the Mac's Git and GitHub credentials. */
  "workspace.pr_open": { class: 'control'; params: {
    workspace_id: string;
    title?: string | null;
    body?: string | null;
    draft?: boolean | null;
  }; result: {
    url: string;
    number: number;
    reused: boolean;
    branch: string;
    target: string;
    repo: string;
    committed: unknown;
    head: string;
  } };
  /** Record a pull request that was opened. */
  "workspace.pr_opened": { class: 'control'; params: {
    workspace_id: string;
    url: string;
    number?: number | null;
  }; result: {
    recorded: boolean;
  } };
  /** Prepare merging back. */
  "workspace.merge_prepare": { class: 'control'; params: {
    workspace_id: string;
    handoff?: boolean | null;
  }; result: unknown };
  /** Say conflicts are resolved. */
  "workspace.merge_resolved": { class: 'control'; params: {
    workspace_id: string;
  }; result: unknown };
  /** Complete merging back. */
  "workspace.merge_complete": { class: 'control'; params: {
    workspace_id: string;
  }; result: unknown };
  /** Abort merging back. */
  "workspace.merge_abort": { class: 'control'; params: {
    workspace_id: string;
  }; result: unknown };
  /** Mark a hunk reviewed. */
  "review.accept": { class: 'control'; params: {
    run_id: string;
    path: string;
    key: string;
    modified_start?: number | null;
    modified_lines?: Array<string> | null;
    base_lines?: Array<string> | null;
    anchor?: string | null;
  }; result: {
    key: string;
    reviewed: boolean;
  } };
  /** Remove a hunk's reviewed mark. */
  "review.unaccept": { class: 'control'; params: {
    run_id: string;
    key: string;
  }; result: {
    key: string;
    reviewed: boolean;
    changed: boolean;
  } };
  /** Hand the daemon marks a surface kept before. */
  "review.import": { class: 'control'; params: {
    run_id: string;
    marks: Array<unknown>;
  }; result: {
    added: number;
  } };
  /** Revert a hunk in the worktree. */
  "review.reject": { class: 'control'; params: {
    workspace_id: string;
    path: string;
    base: string;
    key: string;
  }; result: {
    path: string;
    rejected: boolean;
    file_removed: boolean;
  } };
  /** Add an account profile. */
  "profile.create": { class: 'control'; params: {
    name: string;
    harness: string;
  }; result: Profile };
  /** Rename an account profile. */
  "profile.rename": { class: 'control'; params: {
    id: string;
    name: string;
  }; result: {
    ok: boolean;
  } };
  /** Sign an account profile out. */
  "profile.logout": { class: 'control'; params: {
    id: string;
  }; result: unknown };
  /** Sign in with the provider's device code, in the phone's browser. */
  "profile.device_login": { class: 'control'; params: {
    id: string;
  }; result: {
    profile_id: string;
    finished: boolean;
    url?: string | null;
    code?: string | null;
    valid_ms?: number | null;
    exit?: number | null;
    logged_in?: unknown | null;
    output?: string | null;
  } };
  /** Add an account. */
  "account.create": { class: 'control'; params: {
    provider: string;
    name: string;
  }; result: {
    account: Profile;
    provider: string;
  } };
  /** Remove an account. */
  "account.remove": { class: 'control'; params: {
    id: string;
  }; result: {
    removed: string;
  } };
  /** Stop the daemon. The Mac only: A phone that stopped the daemon could not start it again. */
  "daemon.shutdown": { class: 'mac_only'; params: unknown; result: unknown };
  /** Stop every agent and the daemon. The Mac only: It stops the daemon; a phone uses runs.stop_all. */
  "daemon.stop_all": { class: 'mac_only'; params: unknown; result: unknown };
  /** Post the background notice. The Mac only: It belongs to the Mac's own notifications. */
  "daemon.background_notice": { class: 'mac_only'; params: unknown; result: unknown };
  /** Post a test notification on the Mac. The Mac only: It belongs to the Mac's own notifications. */
  "daemon.test_notice": { class: 'mac_only'; params: unknown; result: unknown };
  /** The sign-in command for a terminal. The Mac only: It needs a terminal on the Mac; a phone uses profile.device_login. */
  "profile.login_command": { class: 'mac_only'; params: unknown; result: unknown };
  /** Phone access: on or off, port, connected phones. The Mac only: Phone access is managed on the Mac. */
  "gateway.status": { class: 'mac_only'; params: unknown; result: unknown };
  /** Turn phone access on. The Mac only: Phone access is switched on the desktop only. */
  "gateway.enable": { class: 'mac_only'; params: unknown; result: unknown };
  /** Turn phone access off. The Mac only: Phone access is switched on the desktop only. */
  "gateway.disable": { class: 'mac_only'; params: unknown; result: unknown };
  /** Read or change gateway settings. The Mac only: Phone access is managed on the Mac. */
  "gateway.settings": { class: 'mac_only'; params: unknown; result: unknown };
  /** Open pairing and return the pairing code. The Mac only: Pairing starts on the Mac. */
  "gateway.pair_start": { class: 'mac_only'; params: unknown; result: unknown };
  /** Close pairing. The Mac only: Pairing starts on the Mac. */
  "gateway.pair_cancel": { class: 'mac_only'; params: unknown; result: unknown };
  /** Accept or decline a phone that asked to pair. The Mac only: The owner confirms on the Mac. */
  "gateway.pair_confirm": { class: 'mac_only'; params: unknown; result: unknown };
  /** Paired devices. The Mac only: Devices are managed on the Mac. */
  "gateway.devices": { class: 'mac_only'; params: unknown; result: unknown };
  /** Revoke a device. The Mac only: A phone that could manage devices could let another one in. */
  "gateway.device_revoke": { class: 'mac_only'; params: unknown; result: unknown };
  /** Change a device's scope. The Mac only: A phone could raise its own scope. */
  "gateway.device_scope": { class: 'mac_only'; params: unknown; result: unknown };
  /** Rename a device. The Mac only: Devices are managed on the Mac. */
  "gateway.device_rename": { class: 'mac_only'; params: unknown; result: unknown };
  /** Whether a VS Code window on the Mac has the focus. The Mac only: It describes the Mac's own windows. */
  "ui.window": { class: 'mac_only'; params: unknown; result: unknown };
  /** Which agent moments become Mac notifications. The Mac only: It belongs to the Mac's own notifications. */
  "notices.get": { class: 'mac_only'; params: unknown; result: unknown };
  /** Choose which agent moments become Mac notifications. The Mac only: It belongs to the Mac's own notifications. */
  "notices.set": { class: 'mac_only'; params: unknown; result: unknown };
  /** Which agent a window on the Mac is looking at. The Mac only: It describes the Mac's own windows. */
  "ui.focus": { class: 'mac_only'; params: unknown; result: unknown };
  /** Audio Mode: on or off, the track and the cues. */
  "audio.get": { class: 'read'; params: Record<string, never>; result: unknown };
  /** The Mac's installed voices for System voice. */
  "audio.voices": { class: 'read'; params: Record<string, never>; result: unknown };
  /** Change Audio Mode. The Mac only: Audio Mode plays on the Mac; it is set there. */
  "audio.set": { class: 'mac_only'; params: unknown; result: unknown };
  /** Play a cue on the Mac. The Mac only: Audio Mode plays on the Mac; it is set there. */
  "audio.preview": { class: 'mac_only'; params: unknown; result: unknown };
  /** Use a private folder of cues in place. The Mac only: It names a folder on the Mac. */
  "audio.import_commander": { class: 'mac_only'; params: unknown; result: unknown };
  /** Online or offline, and whether Continuity is on. */
  "connection.status": { class: 'read'; params: Record<string, never>; result: unknown };
  /** Continuity's state: connection, local model, waits and handoffs. */
  "continuity.status": { class: 'read'; params: Record<string, never>; result: unknown };
  /** Local models and whether each fits this Mac's memory. */
  "local.models": { class: 'read'; params: Record<string, never>; result: unknown };
  /** What is installed locally: Ollama, OpenCode, models. */
  "local.inventory": { class: 'read'; params: Record<string, never>; result: unknown };
  /** The local models Continuity may use. */
  "local.catalogue": { class: 'read'; params: Record<string, never>; result: unknown };
  /** Local model downloads in progress. */
  "local.downloads": { class: 'read'; params: Record<string, never>; result: unknown };
  /** Agents moved to another provider or to local, and back. */
  "continuity.handoffs": { class: 'read'; params: Record<string, never>; result: unknown };
  /** Agents waiting for a provider to come back. */
  "continuity.waits": { class: 'read'; params: Record<string, never>; result: unknown };
  /** Where an agent can be moved to (local, back, a provider). */
  "run.targets": { class: 'read'; params: {
    run_id: string;
  }; result: unknown };
  /** Whether Ollama is installed and running. */
  "ollama.status": { class: 'read'; params: Record<string, never>; result: unknown };
  /** Check the connection now. */
  "connection.check": { class: 'control'; params: Record<string, never>; result: unknown };
  /** Move an agent to local, back, or another provider. */
  "run.handoff": { class: 'control'; params: {
    run_id: string;
    to: string;
    accept_mode?: string | null;
  }; result: unknown };
  /** Retry a waiting agent now. */
  "run.retry_now": { class: 'control'; params: {
    run_id: string;
  }; result: unknown };
  /** Keep an agent where it is instead of moving it. */
  "run.stay": { class: 'control'; params: {
    run_id: string;
  }; result: unknown };
  /** Continuity settings. The Mac only: Continuity is set on the Mac. */
  "settings.get": { class: 'mac_only'; params: unknown; result: unknown };
  /** Change Continuity settings. The Mac only: Continuity is set on the Mac. */
  "settings.set": { class: 'mac_only'; params: unknown; result: unknown };
  /** The first-use notice's state in VS Code. The Mac only: It describes the Mac's own windows. */
  "continuity.ui": { class: 'mac_only'; params: unknown; result: unknown };
  /** Dismiss the first-use notice. The Mac only: It describes the Mac's own windows. */
  "continuity.notice": { class: 'mac_only'; params: unknown; result: unknown };
  /** Offer to download a local model ahead of time. The Mac only: It changes what runs on the Mac and how much of its memory is used. */
  "continuity.prefetch_offer": { class: 'mac_only'; params: unknown; result: unknown };
  /** Choose the local model. The Mac only: It changes what runs on the Mac and how much of its memory is used. */
  "local.pick": { class: 'mac_only'; params: unknown; result: unknown };
  /** Approve a local model download. The Mac only: It changes what runs on the Mac and how much of its memory is used. */
  "local.approve": { class: 'mac_only'; params: unknown; result: unknown };
  /** Load a local model into memory. The Mac only: It changes what runs on the Mac and how much of its memory is used. */
  "local.load": { class: 'mac_only'; params: unknown; result: unknown };
  /** Unload a local model. The Mac only: It changes what runs on the Mac and how much of its memory is used. */
  "local.unload": { class: 'mac_only'; params: unknown; result: unknown };
  /** Download a local model. The Mac only: It changes what runs on the Mac and how much of its memory is used. */
  "local.pull": { class: 'mac_only'; params: unknown; result: unknown };
  /** Cancel a local model download. The Mac only: It changes what runs on the Mac and how much of its memory is used. */
  "local.pull_cancel": { class: 'mac_only'; params: unknown; result: unknown };
  /** Install Ollama. The Mac only: It changes what runs on the Mac and how much of its memory is used. */
  "ollama.install": { class: 'mac_only'; params: unknown; result: unknown };
  /** Start Ollama. The Mac only: It changes what runs on the Mac and how much of its memory is used. */
  "ollama.start": { class: 'mac_only'; params: unknown; result: unknown };
  /** Stop Ollama. The Mac only: It changes what runs on the Mac and how much of its memory is used. */
  "ollama.stop": { class: 'mac_only'; params: unknown; result: unknown };
  /** Age a wait (tests only). The Mac only: A test hook. */
  "continuity.test_age": { class: 'mac_only'; params: unknown; result: unknown };
  /** Every agent, as Overseer sees them. */
  "agents.roster": { class: 'mac_only'; params: unknown; result: unknown };
  /** A digest of what an agent did. */
  "agent.digest": { class: 'mac_only'; params: unknown; result: unknown };
  /** Set or read the area an agent works in. */
  "agent.area": { class: 'mac_only'; params: unknown; result: unknown };
  /** The briefings an agent was given. */
  "agent.briefings": { class: 'mac_only'; params: unknown; result: unknown };
  /** Set how often an agent checks in. */
  "agent.cadence": { class: 'mac_only'; params: unknown; result: unknown };
  /** Turn briefings and the channel on or off. */
  "agent.channel": { class: 'mac_only'; params: unknown; result: unknown };
  /** An agent's check-ins. */
  "agent.check_ins": { class: 'mac_only'; params: unknown; result: unknown };
  /** Add a guardrail to an agent. */
  "agent.guardrail": { class: 'mac_only'; params: unknown; result: unknown };
  /** Remove a guardrail. */
  "agent.guardrail_remove": { class: 'mac_only'; params: unknown; result: unknown };
  /** An agent's guardrails. */
  "agent.guardrails": { class: 'mac_only'; params: unknown; result: unknown };
  /** Hold an agent. */
  "agent.hold": { class: 'mac_only'; params: unknown; result: unknown };
  /** The agents on hold. */
  "agent.holds": { class: 'mac_only'; params: unknown; result: unknown };
  /** Release a held agent. */
  "agent.release": { class: 'mac_only'; params: unknown; result: unknown };
  /** Redirect an agent. */
  "agent.redirect": { class: 'mac_only'; params: unknown; result: unknown };
  /** Refuse shares to an agent. */
  "agent.share_deny": { class: 'mac_only'; params: unknown; result: unknown };
  /** Redirect an agent. */
  "run.redirect": { class: 'mac_only'; params: unknown; result: unknown };
  /** Queue a message for an agent. */
  "run.queue": { class: 'mac_only'; params: unknown; result: unknown };
  /** An agent's queued messages. */
  "run.queued": { class: 'mac_only'; params: unknown; result: unknown };
  /** Remove a queued message. */
  "run.unqueue": { class: 'mac_only'; params: unknown; result: unknown };
  /** The agents' channel. */
  "channel.messages": { class: 'mac_only'; params: unknown; result: unknown };
  /** Conflicts between agents. */
  "conflicts.list": { class: 'mac_only'; params: unknown; result: unknown };
  /** Dismiss a conflict between agents. */
  "conflict.dismiss": { class: 'mac_only'; params: unknown; result: unknown };
  /** Resolve a conflict between agents. */
  "conflict.resolve": { class: 'mac_only'; params: unknown; result: unknown };
  /** What agents shared. */
  "share.list": { class: 'mac_only'; params: unknown; result: unknown };
  /** Withdraw a share. */
  "share.withdraw": { class: 'mac_only'; params: unknown; result: unknown };
  /** Start a watch on an agent. */
  "watch.start": { class: 'mac_only'; params: unknown; result: unknown };
  /** End a watch. */
  "watch.end": { class: 'mac_only'; params: unknown; result: unknown };
  /** The watches. */
  "watch.list": { class: 'mac_only'; params: unknown; result: unknown };
  /** What a watch found. */
  "watch.findings": { class: 'mac_only'; params: unknown; result: unknown };
  /** Overseer's session. */
  "overseer.session": { class: 'mac_only'; params: unknown; result: unknown };
  /** The conversation with Overseer. */
  "overseer.messages": { class: 'mac_only'; params: unknown; result: unknown };
  /** Say something to Overseer. */
  "overseer.send": { class: 'mac_only'; params: unknown; result: unknown };
  /** Open Talk to Overseer: what happened while you were away leads. */
  "overseer.visit": { class: 'mac_only'; params: unknown; result: unknown };
  /** Propose actions for the owner to approve. */
  "overseer.propose": { class: 'mac_only'; params: unknown; result: unknown };
  /** Answer one of Overseer's proposals. */
  "overseer.answer": { class: 'mac_only'; params: unknown; result: unknown };
  /** Cancel one of Overseer's proposals. */
  "overseer.cancel": { class: 'mac_only'; params: unknown; result: unknown };
  /** One of Overseer's cards. */
  "overseer.card": { class: 'mac_only'; params: unknown; result: unknown };
  /** Set how much Overseer does on its own. */
  "overseer.level": { class: 'mac_only'; params: unknown; result: unknown };
  /** Choose the repositories where Overseer may suggest Auto. */
  "overseer.auto_repos": { class: 'mac_only'; params: unknown; result: unknown };
  /** Set Overseer's spending cap. */
  "overseer.cap": { class: 'mac_only'; params: unknown; result: unknown };
  /** Start a fresh Overseer conversation. */
  "overseer.fresh": { class: 'mac_only'; params: unknown; result: unknown };
  /** Rally the agents. */
  "overseer.rally": { class: 'mac_only'; params: unknown; result: unknown };
  /** Scan an agent for conflicts. */
  "overseer.scan": { class: 'mac_only'; params: unknown; result: unknown };
  /** A token for an agent's Overseer tools. The Mac only: It is for the agents' own Overseer tools, never a phone. */
  "overseer.token": { class: 'mac_only'; params: unknown; result: unknown };
  /** The Overseer tools an agent may use. The Mac only: It is for the agents' own Overseer tools, never a phone. */
  "overseer.tools": { class: 'mac_only'; params: unknown; result: unknown };
  /** Run one of Overseer's tools for an agent. The Mac only: It is for the agents' own Overseer tools, never a phone. */
  "overseer.tool": { class: 'mac_only'; params: unknown; result: unknown };
  /** Voice Mode's settings. The Mac only: Voice Mode (Gate R) listens and speaks on the Mac; the phone remote has no voice, as the owner chose. */
  "voice.get": { class: 'mac_only'; params: unknown; result: unknown };
  /** Change Voice Mode's settings. The Mac only: Voice Mode (Gate R) listens and speaks on the Mac; the phone remote has no voice, as the owner chose. */
  "voice.set": { class: 'mac_only'; params: unknown; result: unknown };
  /** Which agent Voice Mode speaks for. The Mac only: Voice Mode (Gate R) listens and speaks on the Mac; the phone remote has no voice, as the owner chose. */
  "voice.focus": { class: 'mac_only'; params: unknown; result: unknown };
  /** Say something to Voice Mode. The Mac only: Voice Mode (Gate R) listens and speaks on the Mac; the phone remote has no voice, as the owner chose. */
  "voice.say": { class: 'mac_only'; params: unknown; result: unknown };
  /** Speak a text aloud on the Mac. The Mac only: Voice Mode (Gate R) listens and speaks on the Mac; the phone remote has no voice, as the owner chose. */
  "voice.speak": { class: 'mac_only'; params: unknown; result: unknown };
  /** Read an agent's answer aloud on the Mac. The Mac only: Voice Mode (Gate R) listens and speaks on the Mac; the phone remote has no voice, as the owner chose. */
  "voice.read_back": { class: 'mac_only'; params: unknown; result: unknown };
  /** Answer by voice. The Mac only: Voice Mode (Gate R) listens and speaks on the Mac; the phone remote has no voice, as the owner chose. */
  "voice.answer": { class: 'mac_only'; params: unknown; result: unknown };
  /** Stop what Voice Mode is doing. The Mac only: Voice Mode (Gate R) listens and speaks on the Mac; the phone remote has no voice, as the owner chose. */
  "voice.cancel": { class: 'mac_only'; params: unknown; result: unknown };
  /** What Voice Mode is waiting to hear. The Mac only: Voice Mode (Gate R) listens and speaks on the Mac; the phone remote has no voice, as the owner chose. */
  "voice.requests": { class: 'mac_only'; params: unknown; result: unknown };
  /** Download a voice. The Mac only: Voice Mode (Gate R) listens and speaks on the Mac; the phone remote has no voice, as the owner chose. */
  "voice.download": { class: 'mac_only'; params: unknown; result: unknown };
  /** Simulate speech for tests. The Mac only: Voice Mode (Gate R) listens and speaks on the Mac; the phone remote has no voice, as the owner chose. */
  "voice.simulate": { class: 'mac_only'; params: unknown; result: unknown };
  /** The app's agent limit and who is running. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "agents.limit.get": { class: 'mac_only'; params: unknown; result: unknown };
  /** Change the app's agent limit. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "agents.limit.set": { class: 'mac_only'; params: unknown; result: unknown };
  /** An Auto child's result for its parent (run-bound bridge). The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "auto.bridge.result": { class: 'mac_only'; params: unknown; result: unknown };
  /** An Auto parent's request to delegate a work unit (run-bound bridge). The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "auto.bridge.submit": { class: 'mac_only'; params: unknown; result: unknown };
  /** Replay a recorded Auto decision from its inputs. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "auto.decision.replay": { class: 'mac_only'; params: unknown; result: unknown };
  /** Choose a route for a work unit and launch its child. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "auto.dispatch": { class: 'mac_only'; params: unknown; result: unknown };
  /** Whether Auto Mode is on. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "auto.mode.get": { class: 'mac_only'; params: unknown; result: unknown };
  /** Turn Auto Mode on or off. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "auto.mode.set": { class: 'mac_only'; params: unknown; result: unknown };
  /** An account's recorded model catalog. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "auto.models.list": { class: 'mac_only'; params: unknown; result: unknown };
  /** Read an account's model catalog (metadata only, no model turn). The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "auto.models.refresh": { class: 'mac_only'; params: unknown; result: unknown };
  /** Inspect OpenCode's local model endpoints. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "auto.opencode.local.inspect": { class: 'mac_only'; params: unknown; result: unknown };
  /** Recorded quota readings. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "auto.quota.list": { class: 'mac_only'; params: unknown; result: unknown };
  /** Read an account's quota (Codex) or its identity and plan (Claude), no model turn. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "auto.quota.refresh": { class: 'mac_only'; params: unknown; result: unknown };
  /** One account's quota state for a model. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "auto.quota.state": { class: 'mac_only'; params: unknown; result: unknown };
  /** The route Auto would choose for a new task. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "auto.root.preview": { class: 'mac_only'; params: unknown; result: unknown };
  /** Start a task on the route Auto chooses. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "auto.start": { class: 'mac_only'; params: unknown; result: unknown };
  /** An account's tool inventory in a repository. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "auto.tools.inspect": { class: 'mac_only'; params: unknown; result: unknown };
  /** Clear the local learning history. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "auto.usage.clear": { class: 'mac_only'; params: unknown; result: unknown };
  /** Export the local learning history. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "auto.usage.export": { class: 'mac_only'; params: unknown; result: unknown };
  /** Recorded usage measurements. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "auto.usage.list": { class: 'mac_only'; params: unknown; result: unknown };
  /** A summary of the local learning history. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "auto.usage.summary": { class: 'mac_only'; params: unknown; result: unknown };
  /** Recorded thread usage estimates. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "auto.usage.thread.list": { class: 'mac_only'; params: unknown; result: unknown };
  /** Read a finished thread's usage estimate. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "auto.usage.thread.refresh": { class: 'mac_only'; params: unknown; result: unknown };
  /** Recorded work observations. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "auto.usage.work.list": { class: 'mac_only'; params: unknown; result: unknown };
  /** The one broker ledger of reports, asks and claims. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "broker.envelopes": { class: 'mac_only'; params: unknown; result: unknown };
  /** The one claim ledger of paths owned by agents and Swarm jobs. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "claims.ledger": { class: 'mac_only'; params: unknown; result: unknown };
  /** Delegate a work unit from a run (managed child). The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "run.delegate": { class: 'mac_only'; params: unknown; result: unknown };
  /** A managed child's result. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "run.result": { class: 'mac_only'; params: unknown; result: unknown };
  /** Acknowledge a Swarm message. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.ack": { class: 'mac_only'; params: unknown; result: unknown };
  /** Admit a Swarm job on a target (booking included). The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.admit": { class: 'mac_only'; params: unknown; result: unknown };
  /** Store a Swarm worker's artifact. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.artifact.put": { class: 'mac_only'; params: unknown; result: unknown };
  /** Confirm a Swarm attempt's process exit. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.attempt.confirm_exit": { class: 'mac_only'; params: unknown; result: unknown };
  /** Register a Swarm attempt. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.attempt.register": { class: 'mac_only'; params: unknown; result: unknown };
  /** Record a Swarm availability snapshot. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.availability.observe": { class: 'mac_only'; params: unknown; result: unknown };
  /** Commit a Swarm run's benefit estimate. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.benefit.commit": { class: 'mac_only'; params: unknown; result: unknown };
  /** Preview a Swarm run's benefit estimate. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.benefit.preview": { class: 'mac_only'; params: unknown; result: unknown };
  /** Claim a Swarm resource. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.claim": { class: 'mac_only'; params: unknown; result: unknown };
  /** Complete a Swarm run with its checks. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.complete": { class: 'mac_only'; params: unknown; result: unknown };
  /** Open a Swarm conflict. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.conflict.open": { class: 'mac_only'; params: unknown; result: unknown };
  /** Resolve a Swarm conflict. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.conflict.resolve": { class: 'mac_only'; params: unknown; result: unknown };
  /** A Swarm run's conflicts. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.conflicts": { class: 'mac_only'; params: unknown; result: unknown };
  /** A Swarm job's context. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.context.get": { class: 'mac_only'; params: unknown; result: unknown };
  /** Grant a Swarm job access to an artifact. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.context.grant": { class: 'mac_only'; params: unknown; result: unknown };
  /** Revoke a Swarm job's access to an artifact. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.context.revoke": { class: 'mac_only'; params: unknown; result: unknown };
  /** A Swarm run's coverage. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.coverage": { class: 'mac_only'; params: unknown; result: unknown };
  /** Create a Swarm run. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.create": { class: 'mac_only'; params: unknown; result: unknown };
  /** Extend a Swarm run's deadline. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.deadline.extend": { class: 'mac_only'; params: unknown; result: unknown };
  /** Accept or reject a Swarm job's result. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.decide": { class: 'mac_only'; params: unknown; result: unknown };
  /** Send a Swarm director's message. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.direct": { class: 'mac_only'; params: unknown; result: unknown };
  /** Claim a batch of a director's inbox. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.director.claim_batch": { class: 'mac_only'; params: unknown; result: unknown };
  /** Complete a director's inbox batch. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.director.complete_batch": { class: 'mac_only'; params: unknown; result: unknown };
  /** Launch a Swarm director. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.director.launch": { class: 'mac_only'; params: unknown; result: unknown };
  /** Begin a Swarm director's ownership. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.director.owner.begin": { class: 'mac_only'; params: unknown; result: unknown };
  /** Expire due Swarm director ownerships. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.director.owner.expire_due": { class: 'mac_only'; params: unknown; result: unknown };
  /** Refresh linked Swarm director ownerships. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.director.owner.refresh_linked": { class: 'mac_only'; params: unknown; result: unknown };
  /** Renew a Swarm director's ownership. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.director.owner.renew": { class: 'mac_only'; params: unknown; result: unknown };
  /** Recover a Swarm director. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.director.recover": { class: 'mac_only'; params: unknown; result: unknown };
  /** A Swarm director's summary. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.director.summary": { class: 'mac_only'; params: unknown; result: unknown };
  /** Dispatch the next Swarm job. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.dispatch.next": { class: 'mac_only'; params: unknown; result: unknown };
  /** Begin a Swarm job's external effect. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.effect.begin": { class: 'mac_only'; params: unknown; result: unknown };
  /** Reconcile a Swarm job's external effect. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.effect.reconcile": { class: 'mac_only'; params: unknown; result: unknown };
  /** Revoke a Swarm estimate. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.estimate.revoke": { class: 'mac_only'; params: unknown; result: unknown };
  /** Merge Swarm findings. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.finding.merge": { class: 'mac_only'; params: unknown; result: unknown };
  /** Record a Swarm finding. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.finding.record": { class: 'mac_only'; params: unknown; result: unknown };
  /** A Swarm run's findings. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.findings": { class: 'mac_only'; params: unknown; result: unknown };
  /** One Swarm run. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.get": { class: 'mac_only'; params: unknown; result: unknown };
  /** Integrate a Swarm job's patch. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.integrate": { class: 'mac_only'; params: unknown; result: unknown };
  /** Persist due Swarm job deadlines. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.job.deadline.persist_due": { class: 'mac_only'; params: unknown; result: unknown };
  /** A Swarm run's jobs. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.jobs": { class: 'mac_only'; params: unknown; result: unknown };
  /** Change a Swarm run's worker limit. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.limit.set": { class: 'mac_only'; params: unknown; result: unknown };
  /** Swarm runs. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.list": { class: 'mac_only'; params: unknown; result: unknown };
  /** A Swarm run's messages. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.messages": { class: 'mac_only'; params: unknown; result: unknown };
  /** Whether the native Swarm director is on. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.native_director.get": { class: 'mac_only'; params: unknown; result: unknown };
  /** Turn the native Swarm director on or off. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.native_director.set": { class: 'mac_only'; params: unknown; result: unknown };
  /** Turn Swarm off for a run. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.off": { class: 'mac_only'; params: unknown; result: unknown };
  /** Record a Swarm worker's partial result. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.partial": { class: 'mac_only'; params: unknown; result: unknown };
  /** Pause a Swarm run. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.pause": { class: 'mac_only'; params: unknown; result: unknown };
  /** Record a Swarm run's plan. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.plan": { class: 'mac_only'; params: unknown; result: unknown };
  /** Preview a Swarm policy. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.policy.preview": { class: 'mac_only'; params: unknown; result: unknown };
  /** Set a Swarm policy. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.policy.set": { class: 'mac_only'; params: unknown; result: unknown };
  /** Persist due Swarm redirects. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.redirect.persist_due": { class: 'mac_only'; params: unknown; result: unknown };
  /** A Swarm worker's report. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.report": { class: 'mac_only'; params: unknown; result: unknown };
  /** A Swarm run's final report. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.report.final": { class: 'mac_only'; params: unknown; result: unknown };
  /** Reproduce a Swarm finding. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.reproduce": { class: 'mac_only'; params: unknown; result: unknown };
  /** Change a Swarm run's requirements. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.requirements.change": { class: 'mac_only'; params: unknown; result: unknown };
  /** Resume a Swarm run. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.resume": { class: 'mac_only'; params: unknown; result: unknown };
  /** Revise a Swarm run's plan. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.revise": { class: 'mac_only'; params: unknown; result: unknown };
  /** Replay a Swarm route decision. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.route.replay": { class: 'mac_only'; params: unknown; result: unknown };
  /** Schedule the next Swarm admission. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.schedule.next": { class: 'mac_only'; params: unknown; result: unknown };
  /** Start a Swarm run from one read-back. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.start": { class: 'mac_only'; params: unknown; result: unknown };
  /** Stop a Swarm run. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.stop": { class: 'mac_only'; params: unknown; result: unknown };
  /** Limit Swarm storage pages (test). The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.storage.limit_pages": { class: 'mac_only'; params: unknown; result: unknown };
  /** Recover Swarm storage. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.storage.recover": { class: 'mac_only'; params: unknown; result: unknown };
  /** Swarm storage status. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.storage.status": { class: 'mac_only'; params: unknown; result: unknown };
  /** Set a Swarm run's targets. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.targets.set": { class: 'mac_only'; params: unknown; result: unknown };
  /** Run a Swarm verification. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.verify": { class: 'mac_only'; params: unknown; result: unknown };
  /** A Swarm worker's brief. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.worker.brief": { class: 'mac_only'; params: unknown; result: unknown };
  /** Launch a Swarm worker. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.worker.launch": { class: 'mac_only'; params: unknown; result: unknown };
  /** A Swarm worker's liveness. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.worker.liveness": { class: 'mac_only'; params: unknown; result: unknown };
  /** Poll Swarm worker liveness. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.worker.liveness.poll": { class: 'mac_only'; params: unknown; result: unknown };
  /** Sample a Swarm worker's liveness (test). The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.worker.liveness.sample": { class: 'mac_only'; params: unknown; result: unknown };
  /** Reconcile a Swarm worker's exit. The Mac only: Auto routing and Swarm come to the phone later (the partial merge, AC-204). */
  "swarm.worker.reconcile": { class: 'mac_only'; params: unknown; result: unknown };
  /** Everything the Mac menu-bar item shows, in one read. The Mac only: The menu-bar item is the Mac's own surface (AC-262); the phone reads state and events. */
  "menubar.snapshot": { class: 'mac_only'; params: Record<string, never>; result: unknown };
  /** Share the reviewed marks VS Code keeps, so every surface counts "to review" the same. The Mac only: Written by VS Code and the TUI on the Mac (AC-262, T-26); the phone reads the marks through state. */
  "review.seen": { class: 'mac_only'; params: {
    marks: unknown;
  }; result: {
    ok: boolean;
    kept: number;
  } };
  /** Send an agent’s paused queue. */
  "run.resume_queue": { class: 'mac_only'; params: unknown; result: unknown };
  /** Clear an agent’s queue. */
  "run.clear_queue": { class: 'mac_only'; params: unknown; result: unknown };
  /** Inspect optional text Mods. */
  "mods.list": { class: 'read'; params: Record<string, never>; result: {
    revision: number;
    installed: Array<unknown>;
    bindings: Array<ModBinding>;
    available_bundled: Array<unknown>;
    unavailable: Array<unknown>;
    support: unknown;
  } };
  /** Manage owner-confirmed text Mods. The Mac only: Local owner control; phone inspection is read-only. */
  "mods.preview": { class: 'mac_only'; params: {
    source: string;
    operation: 'install' | 'update';
  }; result: unknown };
  /** Manage owner-confirmed text Mods. The Mac only: Local owner control; phone inspection is read-only. */
  "mods.install": { class: 'mac_only'; params: {
    preview_id: string;
    confirm: boolean;
  }; result: {
    version: unknown;
    revision: number;
  } };
  /** Set a pinned text Mod binding. The Mac only: Local owner control; phone inspection is read-only. */
  "mods.bind": { class: 'mac_only'; params: {
    binding: ModBindingInput;
    expected_revision: number;
  }; result: {
    binding: ModBinding;
    revision: number;
  } };
  /** Remove a text Mod scope override. The Mac only: Local owner control; phone inspection is read-only. */
  "mods.unbind": { class: 'mac_only'; params: {
    binding_id: string;
    expected_revision: number;
  }; result: {
    revision: number;
  } };
  /** Explain a run's desired and applied Mods. */
  "mods.why": { class: 'read'; params: {
    run_id: string;
  }; result: AppliedMods };
  /** Manage owner-confirmed text Mods. The Mac only: Local owner control; phone inspection is read-only. */
  "mods.remove": { class: 'mac_only'; params: {
    mod_id: string;
    fingerprint: string;
    confirm: boolean;
    expected_revision: number;
  }; result: unknown };
}

export type MethodName = keyof Methods;

/** Methods a phone may call, by what they need. A control method carries a request id. */
export const METHOD_CLASS = {
  "hello": 'self',
  "ping": 'self',
  "events.subscribe": 'self',
  "device.notifications": 'self',
  "state": 'read',
  "harness.list": 'read',
  "profile.list": 'read',
  "profile.status": 'read',
  "repo.inspect": 'read',
  "repo.known": 'read',
  "repo.files": 'read',
  "run.raw_output": 'read',
  "run.turns": 'read',
  "run.active": 'read',
  "events.list": 'read',
  "comparison.options": 'read',
  "workspace.diff": 'read',
  "workspace.status": 'read',
  "workspace.changes": 'read',
  "workspace.tree": 'read',
  "workspace.file": 'read',
  "workspace.hunks": 'read',
  "workspace.cleanup_plan": 'read',
  "workspace.pr_plan": 'read',
  "workspace.merge_plan": 'read',
  "review.marks": 'read',
  "account.list": 'read',
  "account.usage": 'read',
  "search": 'read',
  "daemon.last_notice": 'read',
  "daemon.clients": 'read',
  "task.create": 'control',
  "task.archive": 'control',
  "run.follow_up": 'control',
  "run.interrupt": 'control',
  "run.permission": 'control',
  "runs.stop_all": 'control',
  "workspace.cleanup": 'control',
  "workspace.pr_prepare": 'control',
  "workspace.pr_open": 'control',
  "workspace.pr_opened": 'control',
  "workspace.merge_prepare": 'control',
  "workspace.merge_resolved": 'control',
  "workspace.merge_complete": 'control',
  "workspace.merge_abort": 'control',
  "review.accept": 'control',
  "review.unaccept": 'control',
  "review.import": 'control',
  "review.reject": 'control',
  "profile.create": 'control',
  "profile.rename": 'control',
  "profile.logout": 'control',
  "profile.device_login": 'control',
  "account.create": 'control',
  "account.remove": 'control',
  "daemon.shutdown": 'mac_only',
  "daemon.stop_all": 'mac_only',
  "daemon.background_notice": 'mac_only',
  "daemon.test_notice": 'mac_only',
  "profile.login_command": 'mac_only',
  "gateway.status": 'mac_only',
  "gateway.enable": 'mac_only',
  "gateway.disable": 'mac_only',
  "gateway.settings": 'mac_only',
  "gateway.pair_start": 'mac_only',
  "gateway.pair_cancel": 'mac_only',
  "gateway.pair_confirm": 'mac_only',
  "gateway.devices": 'mac_only',
  "gateway.device_revoke": 'mac_only',
  "gateway.device_scope": 'mac_only',
  "gateway.device_rename": 'mac_only',
  "ui.window": 'mac_only',
  "notices.get": 'mac_only',
  "notices.set": 'mac_only',
  "ui.focus": 'mac_only',
  "audio.get": 'read',
  "audio.voices": 'read',
  "audio.set": 'mac_only',
  "audio.preview": 'mac_only',
  "audio.import_commander": 'mac_only',
  "connection.status": 'read',
  "continuity.status": 'read',
  "local.models": 'read',
  "local.inventory": 'read',
  "local.catalogue": 'read',
  "local.downloads": 'read',
  "continuity.handoffs": 'read',
  "continuity.waits": 'read',
  "run.targets": 'read',
  "ollama.status": 'read',
  "connection.check": 'control',
  "run.handoff": 'control',
  "run.retry_now": 'control',
  "run.stay": 'control',
  "settings.get": 'mac_only',
  "settings.set": 'mac_only',
  "continuity.ui": 'mac_only',
  "continuity.notice": 'mac_only',
  "continuity.prefetch_offer": 'mac_only',
  "local.pick": 'mac_only',
  "local.approve": 'mac_only',
  "local.load": 'mac_only',
  "local.unload": 'mac_only',
  "local.pull": 'mac_only',
  "local.pull_cancel": 'mac_only',
  "ollama.install": 'mac_only',
  "ollama.start": 'mac_only',
  "ollama.stop": 'mac_only',
  "continuity.test_age": 'mac_only',
  "agents.roster": 'mac_only',
  "agent.digest": 'mac_only',
  "agent.area": 'mac_only',
  "agent.briefings": 'mac_only',
  "agent.cadence": 'mac_only',
  "agent.channel": 'mac_only',
  "agent.check_ins": 'mac_only',
  "agent.guardrail": 'mac_only',
  "agent.guardrail_remove": 'mac_only',
  "agent.guardrails": 'mac_only',
  "agent.hold": 'mac_only',
  "agent.holds": 'mac_only',
  "agent.release": 'mac_only',
  "agent.redirect": 'mac_only',
  "agent.share_deny": 'mac_only',
  "run.redirect": 'mac_only',
  "run.queue": 'mac_only',
  "run.queued": 'mac_only',
  "run.unqueue": 'mac_only',
  "channel.messages": 'mac_only',
  "conflicts.list": 'mac_only',
  "conflict.dismiss": 'mac_only',
  "conflict.resolve": 'mac_only',
  "share.list": 'mac_only',
  "share.withdraw": 'mac_only',
  "watch.start": 'mac_only',
  "watch.end": 'mac_only',
  "watch.list": 'mac_only',
  "watch.findings": 'mac_only',
  "overseer.session": 'mac_only',
  "overseer.messages": 'mac_only',
  "overseer.send": 'mac_only',
  "overseer.visit": 'mac_only',
  "overseer.propose": 'mac_only',
  "overseer.answer": 'mac_only',
  "overseer.cancel": 'mac_only',
  "overseer.card": 'mac_only',
  "overseer.level": 'mac_only',
  "overseer.auto_repos": 'mac_only',
  "overseer.cap": 'mac_only',
  "overseer.fresh": 'mac_only',
  "overseer.rally": 'mac_only',
  "overseer.scan": 'mac_only',
  "overseer.token": 'mac_only',
  "overseer.tools": 'mac_only',
  "overseer.tool": 'mac_only',
  "voice.get": 'mac_only',
  "voice.set": 'mac_only',
  "voice.focus": 'mac_only',
  "voice.say": 'mac_only',
  "voice.speak": 'mac_only',
  "voice.read_back": 'mac_only',
  "voice.answer": 'mac_only',
  "voice.cancel": 'mac_only',
  "voice.requests": 'mac_only',
  "voice.download": 'mac_only',
  "voice.simulate": 'mac_only',
  "agents.limit.get": 'mac_only',
  "agents.limit.set": 'mac_only',
  "auto.bridge.result": 'mac_only',
  "auto.bridge.submit": 'mac_only',
  "auto.decision.replay": 'mac_only',
  "auto.dispatch": 'mac_only',
  "auto.mode.get": 'mac_only',
  "auto.mode.set": 'mac_only',
  "auto.models.list": 'mac_only',
  "auto.models.refresh": 'mac_only',
  "auto.opencode.local.inspect": 'mac_only',
  "auto.quota.list": 'mac_only',
  "auto.quota.refresh": 'mac_only',
  "auto.quota.state": 'mac_only',
  "auto.root.preview": 'mac_only',
  "auto.start": 'mac_only',
  "auto.tools.inspect": 'mac_only',
  "auto.usage.clear": 'mac_only',
  "auto.usage.export": 'mac_only',
  "auto.usage.list": 'mac_only',
  "auto.usage.summary": 'mac_only',
  "auto.usage.thread.list": 'mac_only',
  "auto.usage.thread.refresh": 'mac_only',
  "auto.usage.work.list": 'mac_only',
  "broker.envelopes": 'mac_only',
  "claims.ledger": 'mac_only',
  "run.delegate": 'mac_only',
  "run.result": 'mac_only',
  "swarm.ack": 'mac_only',
  "swarm.admit": 'mac_only',
  "swarm.artifact.put": 'mac_only',
  "swarm.attempt.confirm_exit": 'mac_only',
  "swarm.attempt.register": 'mac_only',
  "swarm.availability.observe": 'mac_only',
  "swarm.benefit.commit": 'mac_only',
  "swarm.benefit.preview": 'mac_only',
  "swarm.claim": 'mac_only',
  "swarm.complete": 'mac_only',
  "swarm.conflict.open": 'mac_only',
  "swarm.conflict.resolve": 'mac_only',
  "swarm.conflicts": 'mac_only',
  "swarm.context.get": 'mac_only',
  "swarm.context.grant": 'mac_only',
  "swarm.context.revoke": 'mac_only',
  "swarm.coverage": 'mac_only',
  "swarm.create": 'mac_only',
  "swarm.deadline.extend": 'mac_only',
  "swarm.decide": 'mac_only',
  "swarm.direct": 'mac_only',
  "swarm.director.claim_batch": 'mac_only',
  "swarm.director.complete_batch": 'mac_only',
  "swarm.director.launch": 'mac_only',
  "swarm.director.owner.begin": 'mac_only',
  "swarm.director.owner.expire_due": 'mac_only',
  "swarm.director.owner.refresh_linked": 'mac_only',
  "swarm.director.owner.renew": 'mac_only',
  "swarm.director.recover": 'mac_only',
  "swarm.director.summary": 'mac_only',
  "swarm.dispatch.next": 'mac_only',
  "swarm.effect.begin": 'mac_only',
  "swarm.effect.reconcile": 'mac_only',
  "swarm.estimate.revoke": 'mac_only',
  "swarm.finding.merge": 'mac_only',
  "swarm.finding.record": 'mac_only',
  "swarm.findings": 'mac_only',
  "swarm.get": 'mac_only',
  "swarm.integrate": 'mac_only',
  "swarm.job.deadline.persist_due": 'mac_only',
  "swarm.jobs": 'mac_only',
  "swarm.limit.set": 'mac_only',
  "swarm.list": 'mac_only',
  "swarm.messages": 'mac_only',
  "swarm.native_director.get": 'mac_only',
  "swarm.native_director.set": 'mac_only',
  "swarm.off": 'mac_only',
  "swarm.partial": 'mac_only',
  "swarm.pause": 'mac_only',
  "swarm.plan": 'mac_only',
  "swarm.policy.preview": 'mac_only',
  "swarm.policy.set": 'mac_only',
  "swarm.redirect.persist_due": 'mac_only',
  "swarm.report": 'mac_only',
  "swarm.report.final": 'mac_only',
  "swarm.reproduce": 'mac_only',
  "swarm.requirements.change": 'mac_only',
  "swarm.resume": 'mac_only',
  "swarm.revise": 'mac_only',
  "swarm.route.replay": 'mac_only',
  "swarm.schedule.next": 'mac_only',
  "swarm.start": 'mac_only',
  "swarm.stop": 'mac_only',
  "swarm.storage.limit_pages": 'mac_only',
  "swarm.storage.recover": 'mac_only',
  "swarm.storage.status": 'mac_only',
  "swarm.targets.set": 'mac_only',
  "swarm.verify": 'mac_only',
  "swarm.worker.brief": 'mac_only',
  "swarm.worker.launch": 'mac_only',
  "swarm.worker.liveness": 'mac_only',
  "swarm.worker.liveness.poll": 'mac_only',
  "swarm.worker.liveness.sample": 'mac_only',
  "swarm.worker.reconcile": 'mac_only',
  "menubar.snapshot": 'mac_only',
  "review.seen": 'mac_only',
  "run.resume_queue": 'mac_only',
  "run.clear_queue": 'mac_only',
  "mods.list": 'read',
  "mods.preview": 'mac_only',
  "mods.install": 'mac_only',
  "mods.bind": 'mac_only',
  "mods.unbind": 'mac_only',
  "mods.why": 'read',
  "mods.remove": 'mac_only',
} as const satisfies Record<MethodName, MethodClass>;

export type PhoneMethod = { [K in MethodName]: Methods[K]['class'] extends 'mac_only' ? never : K }[MethodName];
export type ControlMethod = { [K in MethodName]: Methods[K]['class'] extends 'control' ? K : never }[MethodName];
export type Params<M extends MethodName> = Methods[M]['params'];
export type Result<M extends MethodName> = Methods[M]['result'];
