// What the Markdown comparison is run on.
//
// WRITTEN: replies as agents write them, one construct after another. The tree must have the same
// structure as VS Code's page (test/markdown.test.ts).
// UNSAFE: raw HTML, scripts, addresses that run code. The phone must show the same words as VS
// Code's page and nothing else; structure is not compared, because VS Code keeps the few tags its
// sanitizer allows (a raw <strong> is bold there) and the phone shows raw HTML as its text.

const long = 'a'.repeat(30) + 'b'.repeat(40);

export const WRITTEN: ReadonlyArray<string> = [
  'A paragraph.',
  'Two lines\nof one paragraph.\n\nAnother paragraph.',
  '# One\n## Two\n### Three\n#### Four\n##### Five\n###### Six\n####### seven is a paragraph',
  '# Closed heading ##\n\n#hashtag is a paragraph\n\n#\n\n## With `code` and **bold**',
  'Title\n=====\n\nSub title\n---------\n\nafter',
  'Text *emphasis* and **strong** and ***both*** and _under_ and __double__.',
  'snake_case_name stays, 2*3*4 is emphasis, **bold**text, a * b * c',
  'Nested **strong with *emphasis* inside** and *emphasis with **strong** inside*.',
  'Strike ~~gone~~ and ~single~ and ~~~not~~~.',
  'Inline `code`, ``code with ` tick``, ` spaced `, and an unclosed ` tick.',
  'A [link](https://example.com), one with a [title](https://example.com/a "The title"), and <https://auto.example/path>.',
  'A [link with (parentheses)](https://en.wikipedia.org/wiki/Rust_(programming_language)) and [angle](<https://example.com/a b>).',
  'Bare https://example.com/path?query=1. And www.example.org, and http://a.b/c). Mail someone@example.com now.',
  'A [relative](docs/readme.md) link, an [anchor](#top), and a [mail](mailto:a@b.co).',
  '[named][one] and [one] and [two][]\n\n[one]: https://example.com/one "One"\n[two]: <https://example.com/two>',
  'A picture ![alt text](https://example.com/a.png) is not shown.',
  'Hard break with spaces  \nnext line, and with a backslash\\\nnext line.',
  'Escapes: \\*not emphasis\\*, \\# not heading, \\[not a link\\](x), 1\\. not a list, back\\\\slash',
  'Entities: &amp; &lt; &gt; &quot; &#39; &copy; &nbsp;| &#8212; &#x2014; &hellip; &unknown; &amp and AT&T',
  '- one\n- two\n- three',
  '* star\n* list\n\n+ plus\n+ list',
  '1. first\n2. second\n3. third',
  '3. starts at three\n4. four\n\n7) other delimiter\n8) again',
  '- loose one\n\n- loose two\n\n- loose three',
  '- item\n  continued on the next line\n- second\nlazy continuation',
  '- outer\n  - inner\n    - innermost\n  - inner two\n- outer two',
  '1. outer\n   - inner bullet\n   - another\n2. second\n   1. nested number\n   2. again',
  '- item with a paragraph\n\n  second paragraph of the item\n\n- next',
  '- item with code:\n\n  ```js\n  let a = 1;\n  ```\n\n- next',
  '- [ ] to do\n- [x] done\n- [X] also done\n- not a task',
  '- [ ] loose task\n\n- [x] loose done',
  'A paragraph\n- then a list\n- right after it',
  'A paragraph\n2. not a list because it does not start at one',
  '- a\n- b\n\ntext after the list',
  '| Case | Before | After |\n| --- | --- | --- |\n| 3 tabs expire together | 3 refresh calls | 1 refresh call |\n| Refresh fails | stuck spinner | error surfaces once |',
  '| left | center | right |\n|:-----|:------:|------:|\n| `a` | **b** | [c](https://c.example) |',
  'a | b\n--- | ---\n1 | 2\n3 | 4 | 5\n6',
  '| a \\| pipe | b |\n| --- | --- |\n| `x \\| y` | z |',
  'Text before\n\n| one |\n| --- |\n| 1 |\n\nText after',
  'Text right before a table\n| a | b |\n| - | - |\n| 1 | 2 |',
  '```ts\nconst token = await coordinator.refresh(() => api.refreshToken());\n```',
  '```\nno language\n```',
  '```python title="x.py"\nprint("hi")\n```',
  '```c++\nint main() {}\n```\n\n```c#\nclass A {}\n```',
  '~~~sh\necho "tildes"\n~~~',
  '````md\n```js\nnested fence\n```\n````',
  '```js\nunclosed fence\nstill code',
  '    indented code\n    second line\n\nparagraph',
  '```\n' + Array.from({ length: 30 }, (_, i) => `line ${i + 1}`).join('\n') + '\n```',
  '```html\n<script>alert("in code")</script>\n<b>bold?</b> &amp;\n```',
  '> a quote\n> on two lines\n\n> another\nlazy line',
  '> # heading in a quote\n>\n> - list\n> - in a quote\n>\n> ```\n> code\n> ```',
  '> outer\n> > inner\n> back',
  'Above\n\n---\n\nBelow\n\n***\n\n___',
  'Full path for reference: /Users/fixture/projects/shop/src/auth/session-refresh-coordinator.ts — see the [refresh token spec](https://datatracker.ietf.org/doc/html/rfc6749#section-6).',
  `A long token ${long} in prose, and a long one in code \`${long}\`.`,
  'A long path ending a sentence: /fixture/home/worktrees/shop-7ba32f65/delegate-to-a-sub-agent/src/components/Button.tsx.',
  'A long link text is left alone: [https://example.com/' + 'x'.repeat(70) + '](https://example.com/x)',
  '**Long bold /fixture/home/worktrees/shop-7ba32f65/delegate-to-a-sub-agent/src/components/Header.tsx**',
  'Generic types like Map<String, Number> and a < b > c and 1 <2.',
  'Mixed:\n\n1. **Read** `README.md`\n2. *Edit* the file\n   ```diff\n   - old\n   + new\n   ```\n3. Done\n\n| a | b |\n|---|---|\n| 1 | 2 |\n\n> note',
  'Windows line ends\r\nin one paragraph\r\n\r\n- item\r\n- item',
  '\tTab indented code\n\nand *text*',
  'Trailing spaces   \n\n   leading spaces',
  'Emoji and wide text: 😀 **粗体** _斜体_ `代码`',
  '',
  '   ',
  'Line one\\\n',
  '*unclosed emphasis and **unclosed strong',
  'a**b**c and a*b*c and _a_b_ and __a__b',
  '**bold** at start, at end **bold**',
  '1. one\n1. one again\n1. and again',
  '- a\n\n  b\n- c',
  'Header | only\n--- | ---',
  'https://example.com/a_b_c?x=*y* and (https://example.com/in-parens).',
  '**bold *nested** end* and *a **b* c**',
  '* * *\n\n- - -\n\n_ _ _',
  '1) one\n2) two',
  '-\n  after an empty first line\n- next',
  '- a\n   - three spaces\n - one space',
  '- bullet\n  1. nested number with two spaces\n  2. again',
  '- a list\n\n  | a | b |\n  |---|---|\n  | 1 | 2 |\n\n- > a quote in an item\n  > second line',
  'A paragraph\n# then a heading\nand text\n```\ncode right after\n```\nand more\n> quote right after\n\nend',
  'Stars *** in text and ** alone and * alone',
  'Entity in code `&amp; &lt;` and in a block:\n\n```\n&amp; &copy;\n```',
  'See https://example.com/a, then https://example.com/b; (or https://example.com/c) and https://example.com/foo_(bar) and https://example.com/a?b=c&d=e!',
  'WWW.EXAMPLE.COM and HTTP://EXAMPLE.COM/Path and ftp://files.example.com/x.zip',
  'first.last+tag@example.co.uk, and not-an-email@ and @handle',
  '- item\n\nTitle\n-----\n\n1. one\n\nparagraph',
  'a\n\n\n\nb with many empty lines between',
  '## Heading with a [link](https://example.com) and `code` and a trailing space ',
  '| a |\n|---|\n| **bold** and `code` and [link](https://x.example) and ~~gone~~ |',
  '- **Bold item**: text\n- `code item`\n- [link item](https://example.com)\n- *emphasis item*',
  '1. Step one\n\n   ```sh\n   npm install\n   ```\n\n2. Step two\n\n   More text.\n\n3. Step three',
  '> **Note**\n> This is a note with `code`.\n\nAfter.',
  'Line with trailing backslash\\',
  'Underscores __init__.py and my_var_name and _private and trailing_',
  'Quotes "double" and \'single\' and <angle> and a & b',
  '[empty]() and [spaces]( https://example.com/s ) and [](https://example.com/no-text)',
  '[a [nested] bracket](https://example.com/n) and [unclosed(https://example.com)',
  'Code span across\n`two\nlines` here',
  'Tilde fence info\n\n~~~ js extra words\ncode\n~~~',
  '```\n\n```',
  '```js\n```',
  '    code first\n\n    code after an empty line\nnot code',
];

export const UNSAFE: ReadonlyArray<string> = [
  '<script>alert(1)</script>',
  'Before <script>alert(1)</script> after.',
  '<img src=x onerror=alert(1)>',
  'An image <img src="https://example.com/x.png" onerror="alert(1)"> inline.',
  '<b>bold</b> and <i>italic</i> and <u>under</u>',
  '<div onclick="alert(1)">a div</div>',
  '<div>\nblock of html\n</div>\n\nparagraph after',
  '<style>body { display: none }</style>visible',
  '<iframe src="https://example.com"></iframe>text',
  '<a href="javascript:alert(1)">click</a>',
  '[click](javascript:alert(1))',
  '[click](JaVaScRiPt:alert(1))',
  '[click](java\tscript:alert(1))',
  '[data](data:text/html,<script>alert(1)</script>)',
  '[vb](vbscript:msgbox(1))',
  '<javascript:alert(1)>',
  '[file](file:///etc/passwd)',
  '<svg onload=alert(1)><circle r=1></svg>after',
  '<math><mi>x</mi></math>after',
  '<!-- a comment -->shown',
  '<?php echo 1 ?>shown',
  '<textarea>inside</textarea>',
  '<details><summary>More</summary>hidden?</details>',
  '<input type="text" value="x"> <button>press</button>',
  '<form action="https://evil.example"><input name="q"></form>text',
  '<object data="x"></object><embed src="x">text',
  '<span style="color:red" onclick="x()">styled</span>',
  '<p>a paragraph in html</p>',
  '<h1>heading in html</h1>\n\ntext',
  'Text with &lt;script&gt;alert(1)&lt;/script&gt; escaped.',
  '`<script>alert(1)</script>` in code',
  '<SCRIPT SRC=//evil.example/x.js></SCRIPT>text',
  '<scr<script>ipt>alert(1)</script>',
  '<video src=x></video><audio src=x></audio>text',
  '<noscript><b>no</b></noscript>text',
  '<title>t</title>text',
  'line<br>break and <br/> again',
  '<strong>raw strong</strong> and <em>raw em</em> and <code>raw code</code> and <del>raw del</del>',
  '<ul><li>raw item</li><li>second</li></ul>',
  '<table><tr><td>cell</td></tr></table>',
  '<a href="https://example.com" onclick="alert(1)">raw link</a>',
  '<pre>raw pre\n  kept</pre>',
  'Unclosed <b>bold and <script>never closed\n\nnext paragraph is swallowed',
  '<x-custom>custom element</x-custom>',
  '&lt;b&gt;escaped&lt;/b&gt; &amp;amp;',
];
