#!/usr/bin/env node
// Generates src/theme/tokens.generated.ts from the VS Code design source, so the phone and the
// Overseer Dark / Light themes cannot drift (AC-131).
//
//   node scripts/gen-tokens.mjs            write the file
//   node scripts/gen-tokens.mjs --check    exit 1 when the file is missing, stale or hand-edited
//
// Options for tests: --source <dir with tokens.js and build-themes.js>, --out <file>.
//
// Source of every value:
//   extension/design/tokens.js        scale (space, radius, font, weight, line, motion, chat), palettes
//   extension/design/build-themes.js  the easing curve, which tokensCss() writes as --ov-ease
//   phone/design/phone-tokens.json    what the phone adds (touch sizes, the door, springs)

import { createRequire } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const phoneRoot = path.join(here, '..');
const DEFAULT_SOURCE = path.join(phoneRoot, '..', 'extension', 'design');
const DEFAULT_OUT = path.join(phoneRoot, 'src', 'theme', 'tokens.generated.ts');
const PHONE_TOKENS = path.join(phoneRoot, 'design', 'phone-tokens.json');

function parseArgs(argv) {
  const args = { check: false, source: DEFAULT_SOURCE, out: DEFAULT_OUT };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--check') args.check = true;
    else if (arg === '--source' || arg === '--out') {
      const value = argv[i + 1];
      if (!value) throw new Error(`${arg} needs a value`);
      args[arg.slice(2)] = path.resolve(value);
      i += 1;
    } else throw new Error(`unknown argument: ${arg}`);
  }
  return args;
}

/** Loads the CommonJS design source fresh (no module cache), so a changed source is seen. */
function loadSource(sourceDir) {
  const require = createRequire(path.join(sourceDir, 'index.js'));
  for (const id of Object.keys(require.cache))
    if (id.startsWith(sourceDir)) delete require.cache[id];
  const { scale, palettes } = require(path.join(sourceDir, 'tokens.js'));
  const { tokensCss } = require(path.join(sourceDir, 'build-themes.js'));
  if (!scale || !palettes) throw new Error('tokens.js must export scale and palettes');
  if (typeof tokensCss !== 'function') throw new Error('build-themes.js must export tokensCss');
  return { scale, palettes, ease: parseEase(tokensCss()), phone: loadPhoneTokens() };
}

/** The phone's own tokens, without the file's comment. */
function loadPhoneTokens() {
  const { _comment, ...tokens } = JSON.parse(fs.readFileSync(PHONE_TOKENS, 'utf8'));
  void _comment;
  return tokens;
}

/** Reads the four control points of `--ov-ease: cubic-bezier(a, b, c, d)`. */
function parseEase(css) {
  const match = /--ov-ease:\s*cubic-bezier\(([^)]+)\)/.exec(css);
  if (!match) throw new Error('build-themes.js no longer writes --ov-ease as a cubic-bezier');
  const points = match[1].split(',').map((part) => Number(part.trim()));
  if (points.length !== 4 || points.some((point) => !Number.isFinite(point))) {
    throw new Error(`--ov-ease is not four numbers: ${match[1]}`);
  }
  return points;
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/** Writes a plain value as TypeScript source with stable key order (the source's own order). */
function emit(value, indent) {
  const pad = '  '.repeat(indent);
  if (Array.isArray(value)) return `[${value.map((item) => emit(item, indent)).join(', ')}]`;
  if (value !== null && typeof value === 'object') {
    const lines = Object.entries(value).map(([key, item]) => {
      const name =
        IDENTIFIER.test(key) || /^(0|[1-9][0-9]*)$/.test(key) ? key : JSON.stringify(key);
      return `${pad}  ${name}: ${emit(item, indent + 1)},`;
    });
    return `{\n${lines.join('\n')}\n${pad}}`;
  }
  if (typeof value === 'string') return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  if (typeof value === 'number' && Number.isFinite(value)) return String(value);
  if (typeof value === 'boolean') return String(value);
  throw new Error(`cannot write a token of type ${typeof value}`);
}

function render({ scale, palettes, ease, phone }) {
  const { motion: durations, ...rest } = scale;
  if (!durations) throw new Error('tokens.js scale.motion is missing');
  for (const name of ['dark', 'light']) {
    if (!palettes[name]) throw new Error(`tokens.js palettes.${name} is missing`);
  }
  return `// Generated by phone/scripts/gen-tokens.mjs from extension/design/tokens.js,
// extension/design/build-themes.js and phone/design/phone-tokens.json. Do not edit by hand: run \`npm run tokens\`.
// \`npm run tokens:check\` fails when this file differs from its source.

/** Spacing, radii, type scale, weights, line heights and chat layout, as in the VS Code webviews. */
export const scale = ${emit(rest, 0)} as const;

/** Durations in milliseconds and the easing curve (cubic-bezier control points). */
export const motion = ${emit({ duration: durations, ease }, 0)} as const;

/** Overseer Dark and Overseer Light, the same values the VS Code themes are built from. */
export const palettes = ${emit({ dark: palettes.dark, light: palettes.light }, 0)} as const;

/** What the phone adds: touch sizes, the door and the springs (phone/design/phone-tokens.json). */
export const phone = ${emit(phone, 0)} as const;
`;
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const expected = render(loadSource(args.source));
  const shown = path.relative(process.cwd(), args.out) || args.out;
  if (args.check) {
    const actual = fs.existsSync(args.out) ? fs.readFileSync(args.out, 'utf8') : null;
    if (actual === expected) {
      console.log(`tokens: ${shown} matches its source`);
      return 0;
    }
    console.error(
      actual === null
        ? `tokens: ${shown} is missing. Run: npm run tokens`
        : `tokens: ${shown} differs from extension/design (stale or edited by hand). Run: npm run tokens`,
    );
    return 1;
  }
  fs.mkdirSync(path.dirname(args.out), { recursive: true });
  fs.writeFileSync(args.out, expected);
  console.log(`tokens: wrote ${shown}`);
  return 0;
}

try {
  process.exitCode = main();
} catch (error) {
  console.error(`tokens: ${error instanceof Error ? error.message : String(error)}`);
  process.exitCode = 2;
}
