// Writes src/ui/icons.generated.ts (the codicon names the app uses, with their code points)
// and src/ui/logos.generated.ts (the provider logos and Overseer's mark, as SVG text) from the
// extension's own files, so the phone shows the same icons and logos as VS Code.
// `--check` fails when either file differs from its source.
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const phone = join(here, '..');
const media = join(phone, '..', 'extension', 'media');
const check = process.argv.includes('--check');

const css = readFileSync(join(media, 'vendor', 'codicons', 'codicon.css'), 'utf8');
const icons = new Map();
for (const match of css.matchAll(/\.codicon-([a-z0-9-]+):before\s*\{\s*content:\s*"\\([0-9a-fA-F]+)"/g)) {
  if (!icons.has(match[1])) icons.set(match[1], match[2].toLowerCase());
}
if (icons.size < 100) throw new Error(`only ${icons.size} icons found in codicon.css`);

const names = [...icons.keys()].sort();
const iconFile = [
  '// Generated by phone/scripts/gen-icons.mjs from extension/media/vendor/codicons/codicon.css.',
  '// Do not edit by hand: run `npm run icons`.',
  '',
  '/** Every codicon by name, with its code point in the font (assets/fonts/codicon.ttf). */',
  'export const ICONS = {',
  ...names.map((name) => `  ${JSON.stringify(name)}: 0x${icons.get(name)},`),
  '} as const;',
  '',
  'export type IconName = keyof typeof ICONS;',
  '',
].join('\n');

const logos = readdirSync(join(media, 'logos')).filter((f) => f.endsWith('.svg')).sort();
const mark = join(media, 'overseer.svg');
const logoFile = [
  '// Generated by phone/scripts/gen-icons.mjs from extension/media/logos/*.svg and',
  '// extension/media/overseer.svg. Do not edit by hand: run `npm run icons`.',
  '',
  '/** The provider logos, the same files VS Code shows, by name and theme. */',
  'export const LOGOS = {',
  ...logos.map((file) => `  ${JSON.stringify(file.replace(/\.svg$/, ''))}: ${JSON.stringify(readFileSync(join(media, 'logos', file), 'utf8').trim())},`),
  '} as const;',
  '',
  'export type LogoFile = keyof typeof LOGOS;',
  '',
  "/** Overseer's mark (the stand-in until the brand files of AC-142 exist). */",
  `export const MARK = ${JSON.stringify(existsSync(mark) ? readFileSync(mark, 'utf8').trim() : '')};`,
  '',
].join('\n');

let stale = false;
for (const [path, content] of [[join(phone, 'src', 'ui', 'icons.generated.ts'), iconFile], [join(phone, 'src', 'ui', 'logos.generated.ts'), logoFile]]) {
  const current = existsSync(path) ? readFileSync(path, 'utf8') : '';
  if (current === content) continue;
  if (check) {
    console.error(`${path} is not current: run \`npm run icons\``);
    stale = true;
  } else {
    writeFileSync(path, content);
    console.log(`wrote ${path}`);
  }
}
if (!existsSync(join(phone, 'assets', 'fonts', 'codicon.ttf')) || !readFileSync(join(phone, 'assets', 'fonts', 'codicon.ttf')).equals(readFileSync(join(media, 'vendor', 'codicons', 'codicon.ttf')))) {
  console.error('assets/fonts/codicon.ttf differs from the extension\'s font');
  stale = true;
}
process.exit(stale ? 1 : 0);
